Repository nervosnetwork/ckb, pull requests merged in 2018-12, with the labels that each got.

#64 fix: fix IBD sync process
  sync/src/synchronizer/mod.rs
  sync/src/synchronizer/peers.rs
  sync/src/tests/mod.rs
  sync/src/tests/synchronizer.rs
Labels: bug

#110 fix: fix calculation of headers sync timeout
  sync/src/synchronizer/mod.rs
  sync/src/synchronizer/peers.rs
Labels: bug

#95 feat: implement network group and inbound peer eviction
  Cargo.lock
  network/Cargo.toml
  network/src/ckb_service.rs
  network/src/identify_service.rs
  network/src/lib.rs
  network/src/memory_peer_store.rs
  network/src/network.rs
  network/src/network_config.rs
  network/src/network_group.rs
  network/src/network_service.rs
  network/src/outbound_peer_service.rs
  network/src/peer_store.rs
  network/src/peers_registry.rs
  network/src/ping_service.rs
  network/src/protocol.rs
  network/src/tests/mod.rs
  network/src/tests/peers_registry.rs
  sync/src/synchronizer/mod.rs
Labels: enhancement

#114 docs: update README for using a simple shell command to modify the config file
  README.md
Labels: s:revision-needed
