Repository nervosnetwork/ckb, pull requests merged in 2019-09, with the labels that each got.

#1520 perf: resolve indexer store performance issue
  indexer/src/store.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1521 test: Node should fetch blocks from all peers with better chains
  test/src/main.rs
  test/src/specs/sync/block_sync.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1519 fix: indexer store should lock the state when syncing data
  Cargo.lock
  indexer/Cargo.toml
  indexer/src/store.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1522 chore: Adjust testnet/staging difficulty
  docs/hashes.toml
  resource/specs/staging.toml
  resource/specs/testnet.toml
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1525 chore: let sentry capture panics when failed to verify the data from the storage
  store/src/db.rs
  store/src/store.rs
  store/src/transaction.rs
  util/types/src/prelude.rs
Labels: s:ready-to-merge

#1527 feat: Return cell data in get_live_cell rpc
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/module/chain.rs
  rpc/src/test.rs
  test/src/rpc.rs
  util/jsonrpc-types/src/cell.rs
Labels: breaking change, s:ready-to-merge

#1536 fix: Bump timeout for non ancestor block sync integration test
  test/src/specs/sync/block_sync.rs
Labels: backport rc/v0.20, s:ready-to-merge

#1524 chore: tweak orphan rate target
  chain/src/tests/basic.rs
  spec/src/consensus.rs
  util/rational/src/lib.rs
Labels: s:ready-to-merge

#1540 test: make a unit test more flexible
  Cargo.lock
  util/jsonrpc-types/Cargo.toml
  util/jsonrpc-types/src/bytes.rs
Labels: s:ready-to-merge

#1541 chore: hide the implementation details
  util/jsonrpc-types/src/bytes.rs
  util/types/src/conversion/blockchain.rs
Labels: s:ready-to-merge

#1543 chore: reject malformed message asap, don't verify them
  util/types/src/extension/check_data.rs
Labels: s:ready-to-merge

#1528 feat: use molc to handshake
  Cargo.lock
  network/Cargo.toml
Labels: breaking change, s:ready-to-merge

#1545 chore: cleanup schema file
  util/types/schemas/ckb.mol
  util/types/src/generated/types.rs
Labels: s:ready-to-merge

#1542 chore: replace constructor of EpochExt by builder
  script/src/syscalls/mod.rs
  spec/src/consensus.rs
  util/dao/src/lib.rs
  util/types/schemas/ckb.mol
  util/types/src/conversion/storage.rs
  util/types/src/core/extras.rs
  util/types/src/generated/types.rs
Labels: s:ready-to-merge

#1529 docs: Add calculate_dao_maximum_withdraw example
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/test.rs
Labels: s:ready-to-merge

#1533 fix: Consensus constructor should init epoch reward from parameter.
  spec/src/consensus.rs
Labels: backport rc/v0.20, s:ready-to-merge

#1534 fix: Update secp type script hash in genesis
  docs/hashes.toml
  resource/specs/dev.toml
  resource/specs/staging.toml
  resource/specs/testnet.toml
Labels: s:ready-to-merge

#1539 chore: Verify output length when cellbase is validated
  util/types/src/extension/shortcuts.rs
  verification/src/block_verifier.rs
Labels: s:ready-to-merge

#1510 feat: Check system cells lock script when build genesis block
  spec/src/lib.rs
  test/src/specs/indexer/genesis_issued_cells.rs
Labels: s:ready-to-merge

#1547 [ᚬrc/v0.20] fix: Update secp type script hash in genesis
  docs/hashes.toml
  resource/specs/dev.toml
  resource/specs/staging.toml
  resource/specs/testnet.toml
Labels: hotfix

#1538 feat: overall bench
  Cargo.lock
  benches/Cargo.toml
  benches/benches/bench_main.rs
  benches/benches/benchmarks/mod.rs
  benches/benches/benchmarks/overall.rs
  benches/benches/benchmarks/util.rs
Labels: s:ready-to-merge

#1523 chore: remove store#get_ancestor to avoid misuse
  benches/benches/benchmarks/util.rs
  chain/src/tests/basic.rs
  chain/src/tests/util.rs
  store/src/store.rs
Labels: s:ready-to-merge

#1549 fix: Random failure of block_sync_non_ancestor_best_blocks test
  test/src/specs/sync/block_sync.rs
Labels: backport rc/v0.20, s:ready-to-merge, s:waiting-on-reviewers

#1554 [ᚬrc/v0.19] Fix orphan block race storage
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/mod.rs
Labels: backport rc/v0.20

#1551 feat: cellbase output data must be empty
  benches/benches/benchmarks/overall.rs
  ckb-bin/src/subcommand/init.rs
  miner/src/block_assembler.rs
  miner/src/config.rs
  resource/ckb.toml
  test/src/node.rs
  test/src/specs/mining/bootstrap.rs
  test/src/specs/tx_pool/send_secp_tx.rs
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/lib.rs
  verification/src/block_verifier.rs
  verification/src/error.rs
  verification/src/tests/block_verifier.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1550 feat: Headers can only be referenced after maturity period
  rpc/src/module/experiment.rs
  shared/src/snapshot.rs
  shared/src/tx_pool_ext.rs
  store/src/snapshot.rs
  store/src/transaction.rs
  test/src/main.rs
  test/src/specs/tx_pool/mod.rs
  test/src/specs/tx_pool/reference_header_maturity.rs
  util/test-chain-utils/src/mock_store.rs
  util/types/src/core/cell.rs
  verification/src/contextual_block_verifier.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1558 refactor: Expose method to invoke a single script on a transaction
  script/src/lib.rs
  script/src/verify.rs
Labels: s:ready-to-merge

#1557 test: add some tests back: lost some tests when replace `ckb-core` by `ckb-types`
  util/types/src/extension/calc_hash.rs
  util/types/src/extension/capacity.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1559 fix: block serialized size should not include uncles proposals serialized size
  util/types/src/extension/serialized_size.rs
Labels: b:consensus, backport rc/v0.20, s:ready-to-merge, s:waiting-on-reviewers

#1556 fix: Data race between orphan_pool and storage
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/mod.rs
Labels: hotfix, s:ready-to-merge

#1565 chore: let sentry capture more details when failed to `get_locator`
  sync/src/types.rs
Labels: backport rc/v0.20, s:ready-to-merge

#1552 test: Request unverified blocks
  test/src/main.rs
  test/src/specs/sync/block_sync.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1564 chore: fix rpc print_document
  rpc/json/rpc.json
  rpc/src/test.rs
Labels: backport rc/v0.20, s:ready-to-merge

#1575 chore: Bump faster-hex and blake2b-rs versions
  Cargo.lock
  ckb-bin/Cargo.toml
  network/Cargo.toml
  script/Cargo.toml
  util/crypto/Cargo.toml
  util/fixed-hash/core/Cargo.toml
  util/hash/Cargo.toml
  util/jsonrpc-types/Cargo.toml
Labels: s:ready-to-merge

#1560 chore(deps): bump molecule from 0.2.5 to 0.3.1
  Cargo.lock
  Makefile
  util/types/Cargo.toml
  util/types/src/generated/types.rs
Labels: s:ready-to-merge

#1568 feat: indexer configuration
  Cargo.lock
  ckb-bin/src/subcommand/run.rs
  indexer/Cargo.toml
  indexer/src/lib.rs
  indexer/src/store.rs
  indexer/src/types.rs
  resource/ckb.toml
  rpc/Cargo.toml
  rpc/src/service_builder.rs
  rpc/src/test.rs
  util/app-config/Cargo.toml
  util/app-config/src/app_config.rs
  util/app-config/src/lib.rs
Labels: s:ready-to-merge

#1572 test: sleep less time in test
  test/src/specs/sync/chain_forks.rs
Labels: s:ready-to-merge

#1571 feature: is_better_chain uses first-received policy
  chain/src/chain.rs
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/mod.rs
  sync/src/types.rs
  test/src/specs/mining/basic.rs
  test/src/specs/sync/block_sync.rs
  verification/src/tests/uncle_verifier.rs
Labels: s:ready-to-merge

#1586 feat: script package build adjustment
  script/Cargo.toml
  script/build.rs
  script/src/verify.rs
Labels: s:ready-to-merge

#1590 fix: fix genesis dao satoshi gift incorrect calculation
  docs/hashes.toml
  resource/specs/testnet.toml
  util/dao/utils/src/lib.rs
Labels: backport rc/v0.21, s:ready-to-merge

#1587 refactor: Remove global store cache
  Cargo.lock
  benches/benches/benchmarks/always_success.rs
  benches/benches/benchmarks/secp_2in2out.rs
  chain/src/tests/find_fork.rs
  resource/ckb.toml
  script/src/syscalls/mod.rs
  script/src/verify.rs
  shared/src/shared.rs
  shared/src/snapshot.rs
  store/Cargo.toml
  store/src/cache.rs
  store/src/config.rs
  store/src/db.rs
  store/src/lib.rs
  store/src/snapshot.rs
  store/src/store.rs
  store/src/transaction.rs
  sync/src/tests/sync_shared_state.rs
  sync/src/tests/synchronizer.rs
  util/app-config/src/app_config.rs
  util/dao/src/lib.rs
  util/reward-calculator/src/lib.rs
  util/test-chain-utils/src/mock_store.rs
  verification/src/tests/uncle_verifier.rs
Labels: s:ready-to-merge

#1485 feat(Improvement): Compact Block only includes uncle blocks hash
  sync/src/relayer/block_transactions_process.rs
  sync/src/relayer/block_uncles_verifier.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/error.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/block_transactions_process.rs
  sync/src/relayer/tests/compact_block_process.rs
  sync/src/relayer/tests/reconstruct_block.rs
  sync/src/synchronizer/block_pool.rs
  sync/src/types.rs
  util/types/schemas/ckb.mol
  util/types/src/extension/shortcuts.rs
  util/types/src/generated/types.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1591 fix: Use better message for ban log
  network/src/network.rs
  sync/src/relayer/transactions_process.rs
  sync/src/synchronizer/block_process.rs
Labels: backport rc/v0.21, s:ready-to-merge

#1592 feat: rpc strict JSON parsing
  util/jsonrpc-types/src/blockchain.rs
Labels: s:ready-to-merge

#1597 chore(deps): bump criterion from 0.2.11 to 0.3.0
  Cargo.lock
  util/merkle-mountain-range/Cargo.toml
Labels: s:ready-to-merge

#1596 chore: use uint256 to type difficulty
  benches/benches/benchmarks/next_epoch_ext.rs
  util/types/schemas/ckb.mol
  util/types/src/conversion/blockchain.rs
  util/types/src/core/advanced_builders.rs
  util/types/src/extension/std_traits.rs
  util/types/src/generated/types.rs
  verification/src/error.rs
Labels: s:ready-to-merge

#1603 fix: template timestamp should greater than tip timestamp
  chain/src/tests/block_assembler.rs
  tx-pool/src/process/block_template.rs
Labels: s:ready-to-merge

#1608 Fix AddrManager out of index error
  Cargo.lock
  network/Cargo.toml
  network/src/peer_store/addr_manager.rs
  network/src/tests/addr_manager.rs
  network/src/tests/mod.rs
Labels: backport rc/v0.21, s:ready-to-merge, s:waiting-on-reviewers, t:bug

#1602 feat: use zero lock system cells
  docs/hashes.toml
  resource/specs/dev.toml
  resource/specs/staging.toml
  resource/specs/testnet.toml
Labels: s:ready-to-merge

#1607 feat(test): Print panicked logs when node panicked
  test/src/main.rs
Labels: s:ready-to-merge

#1614 Fix tx fee calculation overflow
  tx-pool/src/component/container.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers, t:bug

#1609 fix: Use dao type script hash in dao transaction
  Cargo.lock
  spec/src/consensus.rs
  test/src/lib.rs
  test/src/node.rs
  test/src/specs/dao/dao_tx.rs
  test/src/specs/dao/mod.rs
  test/src/specs/dao/satoshi_dao_occupied.rs
  test/src/specs/tx_pool/send_secp_tx.rs
  util/dao/Cargo.toml
  util/dao/src/lib.rs
  verification/Cargo.toml
  verification/src/tests/transaction_verifier.rs
  verification/src/transaction_verifier.rs
Labels: s:ready-to-merge

#1616 doc: Add RPC docs of get_block_template, submit_block
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/test.rs
Labels: s:ready-to-merge

#1622 fix: default executor misused
  Cargo.lock
  Cargo.toml
  chain/src/chain.rs
  tx-pool/Cargo.toml
  tx-pool/src/service.rs
  util/future-executor/Cargo.toml
  util/future-executor/src/lib.rs
  verification/Cargo.toml
  verification/src/contextual_block_verifier.rs
Labels: backport rc/v0.21, s:ready-to-merge

#1619 fix: peer store persistent
  network/src/config.rs
  network/src/peer_store/peer_store_db.rs
  network/src/services/dump_peer_store.rs
  network/src/tests/peer_store_db.rs
  util/app-config/src/cli.rs
Labels: backport rc/v0.21, s:ready-to-merge, s:waiting-on-reviewers, t:bug

#1601 chore: refactor CyclesLimit and SizeLimit integration test
  test/src/specs/tx_pool/limit.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1623 [ᚬrc/v0.21] fix: default executor misused
  Cargo.lock
  Cargo.toml
  chain/src/chain.rs
  tx-pool/Cargo.toml
  tx-pool/src/service.rs
  util/future-executor/Cargo.toml
  util/future-executor/src/lib.rs
  verification/Cargo.toml
  verification/src/contextual_block_verifier.rs
Labels: hotfix, s:ready-to-merge

#1606 chore: refactor TemplateSizeLimit integration test
  test/src/specs/mining/size_limit.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1618 feat: Change return type of RPC submit block
  rpc/src/module/miner.rs
  test/src/node.rs
  test/src/rpc.rs
Labels: b:rpc, s:ready-to-merge

#1630 chore: Correct typo builder
  shared/src/shared.rs
  tx-pool/src/lib.rs
  tx-pool/src/service.rs
Labels: s:ready-to-merge

#1628 doc: Correct result of get_block_template
  rpc/README.md
  rpc/json/rpc.json
Labels: s:ready-to-merge

#1617 feat: setup issuance schedule
  docs/hashes.toml
  resource/specs/dev.toml
  resource/specs/staging.toml
  resource/specs/testnet.toml
  rpc/README.md
  rpc/json/rpc.json
  spec/src/consensus.rs
  test/integration.toml
  test/src/specs/tx_pool/send_secp_tx.rs
  util/dao/src/lib.rs
Labels: breaking change, s:ready-to-merge

#1625 chore: upgrade p2p and ring
  Cargo.lock
  network/Cargo.toml
  network/src/network.rs
  network/src/protocols/discovery.rs
  network/src/protocols/test.rs
Labels: s:ready-to-merge

#1644 Fix duplicate p2p phase in get_peers
  network/src/lib.rs
  network/src/network.rs
  network/src/peer_store/peer_store_impl.rs
  network/src/peer_store/types.rs
  network/src/tests/peer_store.rs
  rpc/src/module/net.rs
Labels: backport rc/v0.21, backport rc/v0.22, s:ready-to-merge, t:bug

#1621 chore: better name for `serialized_size(..)` methods to avoid ambiguity
  chain/src/chain.rs
  test/src/specs/mining/size_limit.rs
  test/src/specs/tx_pool/limit.rs
  tx-pool/src/pool.rs
  tx-pool/src/process/submit_txs.rs
  util/types/src/core/views.rs
  util/types/src/extension/serialized_size.rs
  verification/src/block_verifier.rs
  verification/src/tests/block_verifier.rs
  verification/src/transaction_verifier.rs
Labels: s:ready-to-merge

#1641 feat: Cycle adjustments
  Cargo.lock
  rpc/README.md
  rpc/json/rpc.json
  script/Cargo.toml
  script/src/cost_model.rs
  script/src/lib.rs
  script/src/syscalls/debugger.rs
  script/src/syscalls/load_cell.rs
  script/src/syscalls/load_cell_data.rs
  script/src/syscalls/load_header.rs
  script/src/syscalls/load_input.rs
  script/src/syscalls/load_script.rs
  script/src/syscalls/load_script_hash.rs
  script/src/syscalls/load_tx_hash.rs
  script/src/syscalls/load_witness.rs
  script/src/syscalls/utils.rs
  script/src/verify.rs
  spec/src/consensus.rs
  test/src/specs/tx_pool/limit.rs
  test/src/specs/tx_pool/send_secp_tx.rs
Labels: s:ready-to-merge

#1647 chore: change `assert_error_eq` from function to macro
  chain/src/tests/basic.rs
  chain/src/tests/delay_verify.rs
  db/src/db.rs
  error/src/lib.rs
  error/src/util.rs
  script/src/verify.rs
  util/types/src/core/cell.rs
  verification/src/tests/block_verifier.rs
  verification/src/tests/commit_verifier.rs
  verification/src/tests/header_verifier.rs
  verification/src/tests/transaction_verifier.rs
  verification/src/tests/uncle_verifier.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1613 fix: use serialized_size while calculate_txs_size_limit
  chain/src/tests/block_assembler.rs
  tx-pool/src/block_assembler/mod.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1651 chore: remove legacy code
  tx-pool/src/pool.rs
Labels: s:ready-to-merge

#1653 chore: Remove repeating get_proposals
  tx-pool/src/process/block_template.rs
Labels: s:ready-to-merge

#1654 chore: remove redundant dependencies for build.rs and tests
  Cargo.lock
  benches/Cargo.toml
  chain/Cargo.toml
  db/Cargo.toml
  devtools/ci/check-cargotoml.sh
  miner/Cargo.toml
  pow/Cargo.toml
  rpc/Cargo.toml
  shared/Cargo.toml
  store/Cargo.toml
  sync/Cargo.toml
  util/reward-calculator/Cargo.toml
  verification/Cargo.toml
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1657 chore: update block assembler template note
  ckb-bin/src/subcommand/init.rs
Labels: s:ready-to-merge

#1656 chore: bump rust toolchain from 1.36.0 to 1.38.0
  .travis.yml
  azure-pipelines.yml
  benches/benches/benchmarks/overall.rs
  chain/src/chain.rs
  db/src/db.rs
  db/src/iter.rs
  docker/hub/Dockerfile
  error/src/internal.rs
  error/src/lib.rs
  network/src/protocols/mod.rs
  network/src/services/dns_seeding/seed_record.rs
  pow/src/lib.rs
  rpc/src/module/alert.rs
  rpc/src/module/net.rs
  rust-toolchain
  script/src/syscalls/debugger.rs
  script/src/syscalls/load_cell.rs
  script/src/syscalls/load_cell_data.rs
  script/src/syscalls/load_header.rs
  script/src/syscalls/load_input.rs
  script/src/type_id.rs
  script/src/verify.rs
  spec/src/lib.rs
  store/src/db.rs
  store/src/snapshot.rs
  store/src/store.rs
  store/src/transaction.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/transactions_process.rs
  sync/src/synchronizer/block_process.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/synchronizer/get_headers_process.rs
  sync/src/synchronizer/headers_process.rs
  sync/src/synchronizer/in_ibd_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/mod.rs
  sync/src/types.rs
  test/src/main.rs
  tx-pool/src/process/submit_txs.rs
  tx-pool/src/service.rs
  util/app-config/src/cli.rs
  util/crypto/src/secp/mod.rs
  util/crypto/src/secp/signature.rs
  util/fixed-hash/core/src/impls.rs
  util/fixed-hash/core/src/serde.rs
  util/fixed-hash/core/src/std_str.rs
  util/instrument/src/export.rs
  util/instrument/src/import.rs
  util/jsonrpc-types/src/bytes.rs
  util/multisig/src/secp256k1.rs
  util/snapshot/src/lib.rs
  util/types/src/core/cell.rs
  verification/src/block_verifier.rs
  verification/src/contextual_block_verifier.rs
  verification/src/error.rs
  verification/src/header_verifier.rs
  verification/src/transaction_verifier.rs
  verification/src/uncles_verifier.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1660 fix: json type number must use hex string
  rpc/README.md
  rpc/json/rpc.json
  tx-pool/src/process/block_template.rs
  util/jsonrpc-types/src/block_template.rs
  util/jsonrpc-types/src/blockchain.rs
Labels: backport rc/v0.22, s:ready-to-merge

#1667 test: fix insufficient_reward on Windows
  test/src/specs/consensus/insufficient_reward.rs
Labels: backport rc/v0.22, s:ready-to-merge

#1670 Submodule init before windows integration test
  Makefile
Labels: s:ready-to-merge, s:waiting-on-reviewers
