Repository nervosnetwork/ckb, pull requests merged in 2019-11, with the labels that each got.

#1779 feat: Upgrade rocksdb with ReadOnlyDB changes
  Cargo.lock
  db/Cargo.toml
Labels: s:ready-to-merge

#1767 chore: code cleanup for `last_block_announcement`
  sync/src/synchronizer/headers_process.rs
  sync/src/types.rs
Labels: s:ready-to-merge

#1770 fix: skip cellbase short-id collision validation
  sync/src/relayer/compact_block_verifier.rs
Labels: s:ready-to-merge

#1789 chore: adjust DEFAULT_BYTES_PER_CYCLES
  tx-pool/src/component/mod.rs
Labels: s:ready-to-merge

#1790 chore: tweak max block interval
  chain/src/tests/basic.rs
  spec/src/consensus.rs
Labels: s:ready-to-merge

#1791 fix: error message on calculate dao max withdraw
  error/src/lib.rs
  rpc/src/module/alert.rs
  rpc/src/module/experiment.rs
  rpc/src/module/pool.rs
  test/src/specs/dao/dao_tx.rs
  test/src/specs/tx_pool/valid_since.rs
Labels: s:ready-to-merge

#1792 fix: Add back to celloutput lost type script
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/module/chain.rs
  util/jsonrpc-types/src/cell.rs
Labels: s:ready-to-merge

#1788 feat: limit tx max ancestors count
  resource/ckb.toml
  rpc/src/module/pool.rs
  test/src/main.rs
  test/src/specs/tx_pool/mod.rs
  test/src/specs/tx_pool/send_arrow_txs.rs
  tx-pool/src/component/container.rs
  tx-pool/src/component/pending.rs
  tx-pool/src/component/proposed.rs
  tx-pool/src/config.rs
  tx-pool/src/error.rs
  tx-pool/src/pool.rs
  tx-pool/src/process/plug.rs
  tx-pool/src/process/submit_txs.rs
Labels: m:security, s:ready-to-merge, t:bug

#1797 feat: allow specify single consensus param in spec
  spec/src/lib.rs
  util/types/src/core/extras.rs
Labels: s:ready-to-merge

#1781 chore: add limit checking to relay message
  network/src/lib.rs
  sync/src/relayer/block_proposal_process.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/get_block_proposal_process.rs
  sync/src/relayer/get_block_transactions_process.rs
  sync/src/relayer/get_transactions_process.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/block_proposal_process.rs
  sync/src/relayer/transaction_hashes_process.rs
Labels: s:ready-to-merge

#1799 feat: disable jemalloc on MacOS
  Cargo.toml
  src/main.rs
Labels: s:ready-to-merge

#1773 chore: code cleanup and add limit checking to `GetBlocks` message
  sync/src/lib.rs
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/get_blocks_process.rs
Labels: s:ready-to-merge

#1803 feat: allow overriding system script cell capacity
  docs/hashes.toml
  resource/specs/testnet.toml
  spec/src/lib.rs
Labels: s:ready-to-merge, urgent

#1805 fix: proposal table bound
  util/proposal-table/src/lib.rs
Labels: s:ready-to-merge, urgent

#1801 fix: Calculate interest with older withdraw header
  util/dao/src/lib.rs
Labels: s:ready-to-merge

#1809 chore: setup alert keys
  util/network-alert/src/alert_signature.toml
Labels: s:ready-to-merge

#1814 chore: only bundle toml files in resource specs
  resource/build.rs
Labels: urgent

#1813 fix: Fix get locator performance bug
  store/src/store.rs
  sync/src/types.rs
Labels: s:ready-to-merge, urgent

#1817 fix: fix SortedTxMap inconsistent descendants links error
  tx-pool/src/component/container.rs
Labels: backport rc/v0.25, s:ready-to-merge

#1802 fix(test): Handle case that sync reply before relay
  test/src/specs/relay/compact_block.rs
Labels: s:ready-to-merge

#1819 fix: txs relay order
  sync/src/relayer/mod.rs
  sync/src/relayer/transaction_hashes_process.rs
  sync/src/relayer/transactions_process.rs
  sync/src/types.rs
  test/src/main.rs
  test/src/specs/tx_pool/mod.rs
  test/src/specs/tx_pool/reorg_proposals.rs
  test/src/specs/tx_pool/txs_relay_order.rs
  test/src/specs/tx_pool/utils.rs
  tx-pool/src/component/entry.rs
  tx-pool/src/component/orphan.rs
  tx-pool/src/process/fetch_txs_with_cycles.rs
  tx-pool/src/process/submit_txs.rs
  tx-pool/src/service.rs
Labels: s:ready-to-merge

#1800 test: 2 phase dao
  test/src/main.rs
  test/src/specs/dao/dao_tx.rs
  test/src/specs/dao/dao_user.rs
  test/src/specs/dao/dao_verifier.rs
  test/src/specs/dao/mod.rs
  test/src/specs/dao/satoshi_dao_occupied.rs
  test/src/specs/dao/utils.rs
  test/src/txo.rs
  test/src/utils.rs
Labels: s:ready-to-merge

#1822 chore: Update mainnet bootnodes
  resource/ckb.toml
Labels: s:ready-to-merge

#1825 chore: tweak testnet spec
  docs/hashes.toml
  resource/specs/testnet.toml
Labels: s:ready-to-merge

#1828 docs: fix a bunch of typos.
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  chain/src/chain.rs
  indexer/src/types.rs
  network/src/network.rs
  network/src/peer_registry.rs
  network/src/peer_store/peer_store_impl.rs
  network/src/peer_store/types.rs
  network/src/services/dns_seeding/mod.rs
  resource/ckb.toml
  rpc/src/test.rs
  script/src/verify.rs
  store/src/store.rs
  sync/src/relayer/transactions_process.rs
  sync/src/synchronizer/in_ibd_process.rs
  sync/src/types.rs
  test/src/specs/relay/compact_block.rs
  test/src/specs/relay/get_block_transactions_process.rs
  test/src/specs/relay/transaction_relay.rs
  test/src/specs/sync/invalid_block.rs
  tx-pool/src/component/commit_txs_scanner.rs
  tx-pool/src/component/entry.rs
  tx-pool/src/component/pending.rs
  util/app-config/src/cli.rs
  util/fee-estimator/src/estimator.rs
Labels: s:ready-to-merge

#1826 chore: print tx_pool error through Display rather than Debug
  tx-pool/src/process/chain_reorg.rs
Labels: s:ready-to-merge

#1829 chore: print ckb version in log
  ckb-bin/src/subcommand/run.rs
Labels: s:ready-to-merge

#1830 chore: ensure commit abbrev in version consistent
  util/build-info/src/lib.rs
Labels: s:ready-to-merge

#1832 chore: reorder jsontypes fields
  util/jsonrpc-types/src/blockchain.rs
Labels: s:ready-to-merge

#1836 feat: Include calculated minimal fee in RPC's error response
  rpc/src/module/pool.rs
  tx-pool/src/error.rs
  tx-pool/src/process/submit_txs.rs
Labels: s:ready-to-merge

#1833 test: Add test vector for extract/pack dao field
  util/dao/utils/src/lib.rs
Labels: s:ready-to-merge

#1837 chore: omit calculate_dao_maximum_withdraw log
  rpc/src/module/experiment.rs
Labels: s:ready-to-merge

#1839 perf: after exiting the ibd mode, the invalid notify should be removed
  chain/src/tests/basic.rs
  network/src/protocols/mod.rs
  sync/src/relayer/tests/helper.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/mod.rs
Labels: s:ready-to-merge

#1850 fix: Skip checksum for now when installing yasm
  devtools/azure/windows-dependencies.yml
Labels: backport rc/v0.25, s:ready-to-merge

#1846 doc: add RPC notices
  devtools/doc/rpc.py
  rpc/README.md
Labels: s:ready-to-merge

#1851 chore: upgrade p2p to 0.2.7
  Cargo.lock
  network/Cargo.toml
  network/src/network.rs
Labels: s:ready-to-merge

#1854 feat: Upgrade ckb-vm to 0.18.1
  Cargo.lock
  script/Cargo.toml
Labels: backport rc/v0.26, s:ready-to-merge
