Repository nervosnetwork/ckb, pull requests merged in 2019-04, with the labels that each got.

#382 fix: reset peer store connection status when setup
  network/src/peer_store/sqlite/db.rs
  network/src/peer_store/sqlite/peer_store.rs
  network/src/tests/sqlite_peer_store.rs
Labels: s:waiting-for-bors

#385 fix: Upgrade p2p fix repeat connection bug
  Cargo.lock
  network/Cargo.toml
Labels: s:waiting-for-bors

#386 fix: flatbuffers vtable `num_fields` overflow
  protocol/src/protocol_generated_verifier.rs
Labels: s:waiting-for-bors

#388 chore: add deserialize for CellWithStatus&CellOutputWithOutPoint
  util/jsonrpc-types/src/cell.rs
Labels: s:waiting-for-bors

#391 fix: Delete invalid copy, invalid type conversion
  network/src/benches/sqlite_peer_store.rs
  network/src/lib.rs
  network/src/network.rs
  network/src/peer.rs
  network/src/peer_store/sqlite/db.rs
  network/src/peer_store/sqlite/peer_store.rs
  network/src/protocols/mod.rs
  network/src/tests/peers_registry.rs
  network/src/tests/sqlite_peer_store.rs
  sync/src/synchronizer/mod.rs
Labels: s:waiting-for-bors

#408 chore: include dir test in ci
  Makefile
Labels: s:waiting-for-bors

#412 chore: add make task to run integration test
  Makefile
  devtools/ci/script.sh
Labels: s:waiting-for-bors

#414 fix: clear tx verfy cache when chain reorg
  shared/src/chain_state.rs
Labels: hotfix, s:waiting-for-bors

#416 chore: ensure cfbc version
  Makefile
Labels: s:waiting-for-bors

#419 chore: use new constructors to make fixed structs more readable
  core/src/script.rs
  script/src/verify.rs
  util/crypto/src/secp/signature.rs
Labels: s:waiting-for-bors

#422 feat: Remove version from Script
  core/src/script.rs
  core/src/transaction.rs
  miner/src/block_assembler.rs
  protocol/src/builder.rs
  protocol/src/convert.rs
  protocol/src/protocol.fbs
  protocol/src/protocol_generated.rs
  protocol/src/protocol_generated_verifier.rs
  script/src/syscalls/mod.rs
  script/src/verify.rs
  spec/src/lib.rs
  util/jsonrpc-types/src/blockchain.rs
Labels: s:waiting-for-bors

#425 feat: bundle app config
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  core/src/script.rs
  db/src/config.rs
  docker/hub/Dockerfile
  docs/ckb-core-dev.md
  docs/configure.md
  docs/get-ckb.md
  docs/quick-start.md
  network/src/config.rs
  nodes_template/default.toml
  nodes_template/miner.toml
  resource/Cargo.toml
  resource/build.rs
  resource/ckb-miner.toml
  resource/ckb.toml
  resource/specs/cells/always_success
  resource/specs/cells/secp256k1_blake2b_lock
  resource/specs/dev.toml
  resource/specs/integration.toml
  resource/specs/testnet.toml
  resource/src/lib.rs
  resource/src/template.rs
  shared/src/shared.rs
  spec/Cargo.toml
  spec/build.rs
  spec/src/lib.rs
  src/cli/args.rs
  src/cli/export.rs
  src/cli/import.rs
  src/cli/miner.rs
  src/cli/mod.rs
  src/helper.rs
  src/main.rs
  src/setup.rs
  src/setup/app_config.rs
  src/setup/args.rs
  src/setup/cli.rs
  src/setup/exit_code.rs
  src/setup/mod.rs
  src/setup/sentry_config.rs
  src/subcommand/cli.rs
  src/subcommand/export.rs
  src/subcommand/import.rs
  src/subcommand/init.rs
  src/subcommand/miner.rs
  src/subcommand/mod.rs
  src/subcommand/run.rs
  src/system.rs
  test/Cargo.toml
  test/fixtures/nodes_template/default.toml
  test/fixtures/nodes_template/spec/cells/always_success
  test/src/main.rs
  test/src/node.rs
  util/dir/Cargo.toml
  util/dir/src/lib.rs
  util/logger/src/lib.rs
Labels: hotfix, s:waiting-on-reviewers

#421 chore: build release packages in travis
  .travis.yml
  devtools/ci/script.sh
  devtools/init/README.md
  devtools/init/linux-systemd/README.md
  devtools/init/linux-systemd/ckb-miner.service
  devtools/init/linux-systemd/ckb.service
Labels: hotfix, s:waiting-on-reviewers

#438 fix: create tempfile in root dir prevent cross-device link
  resource/src/lib.rs
Labels: hotfix

#437 fix: RPC `local_node_info` returns duplicated addr
  network/src/network.rs
Labels: s:waiting-for-bors, s:waiting-on-reviewers

#439 fix: mining bug caused by type changes in RPC
  miner/src/client.rs
Labels: s:waiting-for-bors

#424 fix: apply hotfix for bugs found in test
  Cargo.lock
  network/Cargo.toml
  network/src/network.rs
  network/src/protocols/discovery.rs
  network/src/protocols/mod.rs
  rpc/src/module/pool.rs
  shared/src/chain_state.rs
  shared/src/tx_pool/types.rs
  src/helper.rs
  src/main.rs
  src/subcommand/run.rs
  src/system.rs
  sync/src/relayer/transaction_process.rs
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/mod.rs
  util/Cargo.toml
  util/src/lib.rs
Labels: hotfix, s:waiting-on-reviewers

#441 feat: use hex string represent lock args in config
  miner/src/block_assembler.rs
  miner/src/config.rs
  util/jsonrpc-types/src/blockchain.rs
Labels: s:waiting-for-bors

#449 chore: ckb version tweaks
  build.rs
  util/build-info/src/lib.rs
Labels: hotfix

#451 chore: bump rust toolchain to 1.34.0
  .travis.yml
  Cargo.lock
  chain/src/tests/util.rs
  core/src/block.rs
  core/src/cell.rs
  core/src/uncle.rs
  docker/hub/Dockerfile
  docs/get-ckb.md
  miner/src/block_assembler.rs
  miner/src/miner.rs
  network/src/lib.rs
  network/src/network.rs
  network/src/protocols/mod.rs
  protocol/src/builder.rs
  protocol/src/convert.rs
  rpc/src/module/chain.rs
  rpc/src/module/miner.rs
  rpc/src/module/pool.rs
  rpc/src/module/trace.rs
  rust-toolchain
  shared/src/store.rs
  sync/src/relayer/block_proposal_process.rs
  sync/src/relayer/block_transactions_process.rs
  sync/src/relayer/compact_block.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/get_block_proposal_process.rs
  sync/src/relayer/get_block_transactions_process.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/transaction_process.rs
  sync/src/synchronizer/block_process.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/synchronizer/get_headers_process.rs
  sync/src/synchronizer/headers_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/relayer.rs
  test/src/node.rs
  test/src/specs/mining.rs
  test/src/specs/pool.rs
  util/build-info/src/lib.rs
  util/jsonrpc-types/src/block_template.rs
  util/jsonrpc-types/src/blockchain.rs
  util/jsonrpc-types/src/proposal_short_id.rs
  util/src/lib.rs
  util/src/unstable/mod.rs
  util/src/unstable/try_convert.rs
  verification/Cargo.toml
  verification/src/block_verifier.rs
  verification/src/tests/commit_verifier.rs
  verification/src/transaction_verifier.rs
Labels: s:waiting-for-bors

#452 chore: upgrade p2p dependence
  Cargo.lock
  network/Cargo.toml
  network/src/network.rs
  network/src/protocols/discovery.rs
  network/src/protocols/mod.rs
  shared/src/chain_state.rs
  src/subcommand/run.rs
  sync/src/relayer/mod.rs
  test/src/net.rs
Labels: s:waiting-for-bors

#458 chore: update Dockerfile [skip ci]
  .dockerignore
  README.md
  docker/hub/Dockerfile
  docs/get-ckb.md
  docs/run-ckb-with-docker.md
Labels: hotfix

#448 feat: relay known filter
  Cargo.lock
  network/src/peers_registry.rs
  sync/Cargo.toml
  sync/src/relayer/mod.rs
  sync/src/relayer/transaction_process.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/mod.rs
  sync/src/types.rs
Labels: s:waiting-on-author

#476 Modify jsonrpc types
  miner/src/block_assembler.rs
  rpc/README.md
  rpc/src/module/chain.rs
  util/jsonrpc-types/src/block_template.rs
  util/jsonrpc-types/src/blockchain.rs
  util/jsonrpc-types/src/cell.rs
  util/jsonrpc-types/src/lib.rs
Labels: s:waiting-on-author

#503 feat: rpc resolve tx from pending and staging
  rpc/src/error.rs
  rpc/src/module/pool.rs
  rpc/src/module/trace.rs
  shared/src/chain_state.rs
  shared/src/tx_pool/types.rs
Labels: fixed-integration-tests, s:waiting-on-ci

#511 [v0.9.0] hotfix: fix VM hang bug for certain invalid programs
  Cargo.lock
  script/Cargo.toml
Labels: hotfix

#492 fix: several patches from testnet
  Cargo.lock
  chain/src/chain.rs
  chain/src/tests/basic.rs
  core/Cargo.toml
  core/src/block.rs
  core/src/cell.rs
  miner/src/client.rs
  network/src/peers_registry.rs
  network/src/protocols/discovery.rs
  network/src/protocols/identify.rs
  network/src/protocols/mod.rs
  rpc/Cargo.toml
  rpc/src/module/chain.rs
  rpc/src/module/miner.rs
  script/src/verify.rs
  shared/Cargo.toml
  shared/src/cell_set.rs
  shared/src/chain_state.rs
  shared/src/tests/cell_set.rs
  shared/src/tests/data/no1/cell_set.json
  shared/src/tests/data/no1/cell_set_diff.json
  shared/src/tests/data/no1/txs.json
  shared/src/tests/mod.rs
  shared/src/tx_pool/pool.rs
  shared/src/tx_pool/types.rs
  shared/src/tx_proposal_table.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/transaction_process.rs
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/block_pool.rs
  sync/src/synchronizer/headers_process.rs
  sync/src/synchronizer/mod.rs
  util/jsonrpc-types/src/cell.rs
  verification/Cargo.toml
  verification/src/block_verifier.rs
  verification/src/error.rs
  verification/src/tests/transaction_verifier.rs
  verification/src/transaction_verifier.rs
Labels: hotfix, s:waiting-on-author

#524 chore: enable overflow-checks build flag on release mode
  Makefile
Labels: s:waiting-on-ci

#472 refactor: Make network more reliable
  Cargo.lock
  network/Cargo.toml
  network/src/benches/sqlite_peer_store.rs
  network/src/errors.rs
  network/src/lib.rs
  network/src/network.rs
  network/src/peer.rs
  network/src/peer_registry.rs
  network/src/peer_store.rs
  network/src/peer_store/sqlite.rs
  network/src/peer_store/sqlite/peer_store.rs
  network/src/peers_registry.rs
  network/src/protocols/discovery.rs
  network/src/protocols/feeler.rs
  network/src/protocols/identify.rs
  network/src/protocols/mod.rs
  network/src/protocols/outbound_peer.rs
  network/src/protocols/ping.rs
  network/src/tests/mod.rs
  network/src/tests/peer_registry.rs
  network/src/tests/sqlite_peer_store.rs
  rpc/src/module/miner.rs
  rpc/src/module/pool.rs
  rpc/src/module/trace.rs
  src/subcommand/run.rs
  sync/src/lib.rs
  sync/src/net_time_checker.rs
  sync/src/relayer/block_transactions_process.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/get_block_proposal_process.rs
  sync/src/relayer/get_block_transactions_process.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/transaction_process.rs
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/synchronizer/get_headers_process.rs
  sync/src/synchronizer/headers_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/mod.rs
  sync/src/tests/relayer.rs
  sync/src/tests/synchronizer.rs
  test/src/net.rs
  test/src/specs/protocols.rs
Labels: hotfix

#546 chore: ubuntu apt add -y,avoid manually type Y
  docs/get-ckb.md
Labels: s:waiting-on-ci

#534 chore: Change default ping interval and timeout
  resource/ckb.toml
Labels: s:waiting-on-ci

#553 test: add node connection timeout to integration test
  test/src/node.rs
  test/src/specs/block_sync.rs
  test/src/specs/mod.rs
  test/src/specs/p2p.rs
Labels: s:waiting-on-ci

#561 [ᚬrc/v0.10.0] fix: revert secp256k1_blake160_sighash_all
  resource/specs/cells/secp256k1_blake160_sighash_all
  spec/src/lib.rs
Labels: hotfix

#565 fix: update testnet genesis hash
  resource/specs/testnet.toml
  spec/src/lib.rs
Labels: s:waiting-on-ci

#537 fix: testnet relay
  Cargo.lock
  shared/src/tx_pool/types.rs
  sync/Cargo.toml
  sync/src/relayer/transaction_process.rs
  verification/src/error.rs
Labels: s:waiting-on-author

#566 refactor: merge two transaction rpc interface
  miner/src/block_assembler.rs
  rpc/README.md
  rpc/src/module/chain.rs
  rpc/src/module/pool.rs
  shared/src/chain_state.rs
  shared/src/shared.rs
  shared/src/store.rs
  shared/src/tx_pool/pool.rs
  traits/src/chain_provider.rs
  util/jsonrpc-types/src/blockchain.rs
  util/jsonrpc-types/src/lib.rs
  verification/src/tests/dummy.rs
Labels: s:waiting-on-ci
