Repository nervosnetwork/ckb, pull requests merged in 2019-03, with the labels that each got.

#294 feat: Use blake2b as the hash function uniformly
  Cargo.lock
  chain/src/tests/find_fork.rs
  core/src/header.rs
  core/src/script.rs
  core/src/transaction.rs
  core/src/uncle.rs
  nodes_template/default.toml
  pow/src/cuckoo.rs
  pow/src/lib.rs
  protocol/src/lib.rs
  script/src/syscalls/mod.rs
  spec/src/lib.rs
  test/fixtures/nodes_template/default.toml
  util/hash/Cargo.toml
  util/hash/src/lib.rs
  util/merkle-tree/Cargo.toml
  util/merkle-tree/src/lib.rs
Labels: v:testnet

#295 Replace p2p library
  Cargo.lock
  network/Cargo.toml
  network/src/benches/sqlite_peer_store.rs
  network/src/ckb_protocol.rs
  network/src/ckb_service.rs
  network/src/errors.rs
  network/src/lib.rs
  network/src/network.rs
  network/src/network_config.rs
  network/src/network_group.rs
  network/src/network_service.rs
  network/src/outbound_peer_service.rs
  network/src/peer_store.rs
  network/src/peer_store/db.rs
  network/src/peer_store/sqlite_peer_store.rs
  network/src/peers_registry.rs
  network/src/ping_service.rs
  network/src/protocol.rs
  network/src/protocol_handler.rs
  network/src/protocol_service.rs
  network/src/service.rs
  network/src/service/ckb_service.rs
  network/src/service/identify_service.rs
  network/src/service/outbound_peer_service.rs
  network/src/service/ping_service.rs
  network/src/service/timer_service.rs
  network/src/tests/peers_registry.rs
  network/src/tests/sqlite_peer_store.rs
  network/src/timer_service.rs
  network/src/transport.rs
  nodes_template/default.toml
  rpc/src/module/miner.rs
  rpc/src/module/pool.rs
  rpc/src/module/trace.rs
  src/cli/run_impl.rs
  sync/src/lib.rs
  sync/src/net_time_checker.rs
  sync/src/relayer/mod.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/mod.rs
  sync/src/tests/relayer.rs
  sync/src/tests/synchronizer.rs
  test/fixtures/nodes_template/default.toml
  util/crypto/Cargo.toml
  util/crypto/src/secp/generator.rs
  util/crypto/src/secp/mod.rs
  util/crypto/src/secp/privkey.rs
  util/crypto/src/secp/pubkey.rs
  util/crypto/src/secp/signature.rs
Labels: t:enhancement

#334 feat: version verification
  core/src/header.rs
  core/src/transaction.rs
  verification/src/error.rs
  verification/src/header_verifier.rs
  verification/src/transaction_verifier.rs
Labels: s:waiting-for-bors

#335 feat: enforce `type` field of a cellbase output cell must be absent
  verification/src/block_verifier.rs
  verification/src/error.rs
  verification/src/tests/block_verifier.rs
  verification/src/transaction_verifier.rs
Labels: s:waiting-for-bors

#342 perf: shrink lock-acquisition
  rpc/src/module/trace.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/transaction_process.rs
  sync/src/synchronizer/mod.rs
Labels: s:waiting-for-bors

#348 chore: rename doc.md to README.md
  rpc/README.md
Labels: s:waiting-for-bors

#346 refactor: replace unwrap with expect
  chain/src/chain.rs
  core/src/header.rs
  core/src/script.rs
  core/src/transaction.rs
  core/src/uncle.rs
  db/src/diskdb.rs
  network/src/network_service.rs
  network/src/protocol.rs
  pow/src/cuckoo.rs
  protocol/src/lib.rs
  rpc/src/server.rs
  spec/src/lib.rs
  src/cli/miner.rs
  util/build-info/src/lib.rs
  util/logger/src/lib.rs
Labels: s:waiting-for-bors

#350 feat: use TryFrom convert protocol
  Cargo.lock
  Makefile
  network/src/service/discovery_service.rs
  protocol/Cargo.toml
  protocol/src/builder.rs
  protocol/src/convert.rs
  protocol/src/error.rs
  protocol/src/lib.rs
  sync/src/relayer/block_proposal_process.rs
  sync/src/relayer/block_transactions_process.rs
  sync/src/relayer/compact_block.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/get_block_proposal_process.rs
  sync/src/relayer/get_block_transactions_process.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/transaction_process.rs
  sync/src/synchronizer/block_process.rs
  sync/src/synchronizer/filter_process.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/synchronizer/get_headers_process.rs
  sync/src/synchronizer/headers_process.rs
  sync/src/synchronizer/mod.rs
  util/src/lib.rs
  util/src/unstable/mod.rs
  util/src/unstable/try_convert.rs
Labels: s:waiting-for-bors

#336 feature: index whether a tx is a cellbase in the chain
  core/src/transaction_meta.rs
  shared/src/cell_set.rs
  shared/src/shared.rs
Labels: s:waiting-for-bors, s:waiting-on-reviewers, s:waiting-on-team

#359 refactor: merge cell_set chain_state cell provider
  chain/src/chain.rs
  chain/src/tests/basic.rs
  shared/src/chain_state.rs
Labels: s:waiting-for-bors

#366 docs: rm docs/data-structures.md [skip ci]
  docs/data-structures.md
Labels: t:doc

#373 Remove cli type_hash subcommand as it's no longer supported
  src/cli/args.rs
Labels: s:waiting-for-bors
