Repository nervosnetwork/ckb, pull requests merged in 2019-12, with the labels that each got.

#1852 docs: add RPC warning in config file
  resource/ckb.toml
Labels: s:ready-to-merge

#1849 feat: no debug symbols as default and add a command to build with debug symbols
  devtools/azure/windows-dependencies.yml
  devtools/doc/rpc.py
  rpc/README.md
Labels: backport rc/v0.26, s:ready-to-merge

#1853 feat: Update error message and prompt of ckb init subcommand
  ckb-bin/src/subcommand/init.rs
Labels: s:ready-to-merge

#1862 refactor: move main chain shortcut to get_ancestor
  sync/src/types.rs
Labels: s:ready-to-merge

#1863 fix: fetch_random_addrs should be able to return peers addrs
  network/src/peer_store/peer_store_impl.rs
  network/src/tests/peer_store.rs
Labels: backport rc/v0.26, s:ready-to-merge

#1868 chore: Remove ckb cli sub-command
  Cargo.lock
  ckb-bin/Cargo.toml
  ckb-bin/src/lib.rs
  ckb-bin/src/subcommand/cli/blake.rs
  ckb-bin/src/subcommand/cli/mod.rs
  ckb-bin/src/subcommand/cli/secp256k1_lock.rs
  ckb-bin/src/subcommand/list_hashes.rs
  ckb-bin/src/subcommand/mod.rs
  resource/ckb.toml
  util/app-config/src/cli.rs
Labels: s:ready-to-merge

#1865 chore: send_transaction rpc doc tweak
  rpc/README.md
  rpc/json/rpc.json
Labels: s:ready-to-merge

#1876 chore(deps): remove dependency `serde_derive`
  Cargo.lock
  ckb-bin/Cargo.toml
  ckb-bin/src/subcommand/list_hashes.rs
  db/Cargo.toml
  db/src/config.rs
  devtools/ci/check-cargotoml.sh
  indexer/Cargo.toml
  indexer/src/types.rs
  miner/Cargo.toml
  miner/src/config.rs
  miner/src/worker/dummy.rs
  miner/src/worker/eaglesong_simple.rs
  network/Cargo.toml
  network/src/config.rs
  pow/Cargo.toml
  pow/src/lib.rs
  resource/Cargo.toml
  resource/src/lib.rs
  rpc/Cargo.toml
  rpc/src/config.rs
  rpc/src/test.rs
  script/Cargo.toml
  script/src/verify.rs
  spec/Cargo.toml
  spec/src/lib.rs
  store/Cargo.toml
  store/src/config.rs
  tx-pool/Cargo.toml
  tx-pool/src/config.rs
  util/app-config/Cargo.toml
  util/app-config/src/app_config.rs
  util/app-config/src/sentry_config.rs
  util/fee-estimator/Cargo.toml
  util/fee-estimator/src/fee_rate.rs
  util/fixed-hash/core/Cargo.toml
  util/jsonrpc-types/Cargo.toml
  util/jsonrpc-types/src/alert.rs
  util/jsonrpc-types/src/block_template.rs
  util/jsonrpc-types/src/blockchain.rs
  util/jsonrpc-types/src/bytes.rs
  util/jsonrpc-types/src/cell.rs
  util/jsonrpc-types/src/chain_info.rs
  util/jsonrpc-types/src/experiment.rs
  util/jsonrpc-types/src/indexer.rs
  util/jsonrpc-types/src/lib.rs
  util/jsonrpc-types/src/net.rs
  util/jsonrpc-types/src/pool.rs
  util/jsonrpc-types/src/sync.rs
  util/logger/Cargo.toml
  util/logger/src/lib.rs
  util/network-alert/Cargo.toml
  util/network-alert/src/config.rs
  util/occupied-capacity/core/Cargo.toml
  util/occupied-capacity/core/src/units.rs
Labels: dependencies, s:ready-to-merge

#1874 fix: remove duplicate p2p phase in discovery protocol
  network/src/peer_store/peer_store_impl.rs
  network/src/peer_store/types.rs
  network/src/protocols/discovery.rs
Labels: s:ready-to-merge

#1875 feat: move feeler behind identify
  network/src/network.rs
  network/src/protocols/identify.rs
Labels: s:ready-to-merge

#1873 fix: ban peer that are not on the same network
  network/src/protocols/identify.rs
Labels: s:ready-to-merge

#1859 fix: fix lost sync/relayer protocol registration
  network/src/network.rs
  network/src/protocols/mod.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/helper.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/mod.rs
Labels: s:ready-to-merge

#1888 feat: add `get_capacity_by_lock_hash` rpc
  indexer/src/store.rs
  indexer/src/types.rs
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/module/indexer.rs
  rpc/src/test.rs
  util/jsonrpc-types/src/indexer.rs
  util/jsonrpc-types/src/lib.rs
Labels: urgent

#1883 chore: auto init ckb dir in Docker
  .dockerignore
  docker/docker-entrypoint.sh
  docker/hub/Dockerfile
  docs/run-ckb-with-docker.md
Labels: backport rc/v0.26, s:ready-to-merge, urgent

#1889 fix: get_cell_meta should return None if output index is not exists
  store/src/store.rs
Labels: backport rc/v0.26, s:ready-to-merge

#1878 test: get_block_template transactions selection
  test/src/main.rs
  test/src/specs/mining/mod.rs
  test/src/specs/mining/tx_select.rs
Labels: s:ready-to-merge

#1890 feat(spec): configurable block bytes limit
  spec/src/consensus.rs
  spec/src/lib.rs
Labels: s:ready-to-merge

#1894 perf: Reduce useless clone / to_owned use
  chain/src/chain.rs
  ckb-bin/src/subcommand/import.rs
  ckb-bin/src/subcommand/run.rs
  indexer/src/store.rs
  network/src/network.rs
  network/src/peer_store/peer_store_impl.rs
  network/src/protocols/mod.rs
  network/src/services/dump_peer_store.rs
  resource/src/template.rs
  rpc/src/module/chain.rs
  rpc/src/module/pool.rs
  rpc/src/module/stats.rs
  rpc/src/service_builder.rs
  shared/src/shared.rs
  spec/src/lib.rs
  sync/src/orphan_block_pool.rs
  sync/src/relayer/block_transactions_process.rs
  sync/src/relayer/block_uncles_verifier.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/synchronizer/block_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/types.rs
  tx-pool/src/component/pending.rs
  tx-pool/src/component/proposed.rs
  util/test-chain-utils/src/mock_store.rs
  util/types/src/conversion/storage.rs
  util/types/src/core/cell.rs
  verification/src/contextual_block_verifier.rs
  verification/src/header_verifier.rs
Labels: s:ready-to-merge

#1897 test: move dail different net behind dail same net
  network/src/protocols/test.rs
Labels: s:ready-to-merge

#1895 fix: fix peer store saving failed due to temp dir not exists
  network/src/peer_store/peer_store_db.rs
Labels: backport rc/v0.26, s:ready-to-merge

#1899 fix(tests): rpc server should explicit close
  rpc/src/test.rs
Labels: s:ready-to-merge

#1891 feat: notify service
  Cargo.lock
  Cargo.toml
  chain/src/chain.rs
  ckb-bin/src/subcommand/run.rs
  notify/Cargo.toml
  notify/src/lib.rs
  resource/ckb.toml
  rpc/Cargo.toml
  rpc/src/module/alert.rs
  rpc/src/module/stats.rs
  rpc/src/test.rs
  shared/Cargo.toml
  shared/src/shared.rs
  util/app-config/Cargo.toml
  util/app-config/src/app_config.rs
  util/network-alert/Cargo.toml
  util/network-alert/src/alert_relayer.rs
  util/network-alert/src/config.rs
  util/network-alert/src/notifier.rs
  util/network-alert/src/tests/test_notifier.rs
Labels: breaking change
