Repository nervosnetwork/ckb, pull requests merged in 2019-07, with the labels that each got.

#1143 [ᚬrc/v0.15.z] fix: get_ancestor consistent
  Cargo.lock
  chain/src/chain.rs
  shared/src/shared.rs
  util/reward-calculator/Cargo.toml
  util/reward-calculator/src/lib.rs
Labels: hotfix

#1148 [ᚬrc/v0.15.z] fix: sync block download filter
  sync/src/synchronizer/block_fetcher.rs
Labels: hotfix

#1147 [ᚬrc/v0.15.z] Add alert pubkeys
  util/network-alert/src/alert.toml
Labels: hotfix

#1164 [ᚬrc/v0.15.z] fix: Ban peer when validate received block failed
  sync/src/synchronizer/block_process.rs
  sync/src/synchronizer/mod.rs
Labels: hotfix

#1167 [ᚬrc/v0.15.z] fix: proposal reward calculate consistency
  chain/src/chain.rs
  util/reward-calculator/src/lib.rs
Labels: hotfix

#1169 [ᚬrc/v0.15.z] fix: only sync with outbound peer in IBD mode
  sync/src/synchronizer/mod.rs
  sync/src/types.rs
Labels: hotfix

#1151 [ᚬrc/v0.15.z] feat: allow providing extra sentry info in config
  resource/ckb-miner.toml
  resource/ckb.toml
  util/app-config/src/sentry_config.rs
Labels: hotfix

#1176 [ᚬrc/v0.15.z] fix: Use tip header to ignore compact block
  sync/src/relayer/compact_block_process.rs
Labels: hotfix

#1172 [ᚬrc/v0.15.z] test: fix integration test for #1169
  test/src/main.rs
  test/src/specs/p2p/malformed_message.rs
  test/src/specs/sync/block_sync.rs
  test/src/specs/sync/chain_forks.rs
  test/src/specs/sync/invalid_locator_size.rs
  test/src/specs/sync/sync_timeout.rs
Labels: hotfix

#1150 fix: correct block number from tx_pool_excutor
  shared/tx-pool-executor/src/tx_pool_executor.rs
Labels: breaking change, t:bug

#1195 [ᚬrc/v0.15.z] hotfix rc0.15
  benches/benches/process_block.rs
  chain/src/chain.rs
  chain/src/tests/basic.rs
  store/src/store.rs
  sync/src/synchronizer/block_process.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/synchronizer/headers_process.rs
  sync/src/synchronizer/mod.rs
Labels: hotfix

#1179 [ᚬrc/v0.15.z] fix: random failure caused by dirty exit in RPC test
  rpc/src/test.rs
Labels: backport, hotfix

#1196 fix: reserved only do nothing except for connect all reserved peers
  network/src/services/outbound_peer.rs
Labels: backport rc/v0.15.z

#1183 [ᚬrc/v0.15.z] fix: ibd should remain false once returned false
  sync/src/types.rs
Labels: backport, hotfix

#1190 [ᚬrc/v0.15.z] fix: fix sync logic
  sync/src/synchronizer/mod.rs
  sync/src/types.rs
Labels: backport, hotfix

#1189 [ᚬrc/v0.15.z] fix: fix debug log state error
  sync/src/synchronizer/headers_process.rs
Labels: backport, hotfix

#1185 [ᚬrc/v0.15.z] fix: resolve fresh proposal txs checking bug
  sync/src/relayer/mod.rs
Labels: backport, hotfix

#1014 fix: locate blocks by hash
  chain/src/tests/basic.rs
  core/src/cell.rs
  core/src/transaction_meta.rs
  protos/schemas/common.fbs
  protos/src/convert/from_common.rs
  protos/src/convert/to_common.rs
  protos/src/generated/common.rs
  script/src/verify.rs
  shared/src/cell_set.rs
  shared/src/chain_state.rs
  shared/tx-pool-executor/src/tx_pool_executor.rs
  store/src/store.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/synchronizer/headers_process.rs
  traits/src/block_median_time_context.rs
  verification/src/contextual_block_verifier.rs
  verification/src/tests/transaction_verifier.rs
  verification/src/transaction_verifier.rs
Labels: breaking change

#1214 fix: Reset current_time of block template
  miner/src/block_assembler.rs
Labels: backport rc/v0.15.z

#1140 perf: shrink chain state lock scope in relayer
  sync/src/relayer/block_transactions_process.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/reconstruct_block.rs
Labels: s:waiting-on-author

#1227 fix: should check tx from pool when the short_id set is not empty
  sync/src/relayer/mod.rs
Labels: backport rc/v0.16

#1238 fix: build.rs failed without git dir
  build.rs
Labels: backport rc/v0.16

#1228 [ᚬrc/v0.16] fix(relayer): should check tx from tx_pool when the short_id set is not empty
  sync/src/relayer/mod.rs
Labels: backported, hotfix

#1232 feat: IBD with whitelist
  network/src/config.rs
  network/src/network.rs
  network/src/peer.rs
  network/src/peer_registry.rs
  network/src/protocols/test.rs
  network/src/services/outbound_peer.rs
  network/src/tests/peer_registry.rs
  resource/ckb.toml
  sync/src/synchronizer/headers_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/types.rs
  test/src/net.rs
Labels: b:cli, breaking change

#1256 chore: fix ci
  Cargo.lock
  devtools/doc/rpc.py
  rpc/README.md
  rpc/json/rpc.json
  sync/src/relayer/tests/helper.rs
Labels: s:ready-to-merge

#1248 chore: upgrade rustc to 1.36.0
  .travis.yml
  azure-pipelines.yml
  docker/hub/Dockerfile
  rust-toolchain
  shared/src/tx_pool/proposed.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1258 feat: only allow default secp256k1 block assembler
  ckb-bin/src/lib.rs
  ckb-bin/src/subcommand/init.rs
  ckb-bin/src/subcommand/run.rs
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/lib.rs
Labels: s:ready-to-merge

#1233 test: Relay block contains not-fresh tx
  sync/src/relayer/block_transactions_process.rs
  test/src/main.rs
  test/src/specs/relay/compact_block.rs
Labels: s:ready-to-merge

#1237 feat: cache BLOCK_INVALID/BLOCK_VALID status
  sync/src/block_status.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/tests/sync_shared_state.rs
  sync/src/tests/util.rs
  sync/src/types.rs
Labels: s:ready-to-merge

#1254 chore: routine to filter sentry events
  util/app-config/src/sentry_config.rs
Labels: s:ready-to-merge

#1262 chore(dependencies): lock parking-lot version
  Cargo.lock
Labels: s:ready-to-merge

#1261 chore: fix ckb stats example
  util/app-config/src/cli.rs
Labels: s:ready-to-merge

#1275 chore: clippy
  test/src/main.rs
  test/src/node.rs
Labels: s:ready-to-merge

#1274 feat: adjust max block interval to 30s
  spec/src/consensus.rs
Labels: b:consensus, breaking change, m:consensus, s:ready-to-merge

#1277 chore(ci): do not repeat integration test in develop
  .travis.yml
Labels: s:ready-to-merge

#1282 fix: byte index is not a char boundary for non-ASCII char
  ckb-bin/src/subcommand/cli/mod.rs
  util/jsonrpc-types/src/bytes.rs
  util/jsonrpc-types/src/proposal_short_id.rs
Labels: s:ready-to-merge

#1268 fix: shoud not reject not better compact block
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/error.rs
  sync/src/relayer/tests/compact_block_process.rs
Labels: s:ready-to-merge

#1283 chore: update block status if header invalid
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/tests/compact_block_process.rs
Labels: s:ready-to-merge

#1284 test: re-export p2p from network
  Cargo.lock
  sync/Cargo.toml
  sync/src/relayer/tests/helper.rs
Labels: s:ready-to-merge

#1276 chore: use gnu grep in check-cargotoml.sh
  devtools/ci/check-cargotoml.sh
Labels: s:ready-to-merge

#1291 chore: add debug log to Relayer#reconstruct_block
  sync/src/relayer/mod.rs
Labels: s:ready-to-merge

#1289 feat: Add RPC broadcast_transaction
  rpc/src/module/test.rs
Labels: s:ready-to-merge

#1280 refactor: explicit deny alert when version not match
  util/network-alert/src/notifier.rs
Labels: s:ready-to-merge

#1301 [ᚬrc/v0.17] feature: add get_block_finalized_reward_info rpc
  chain/src/tests/reward.rs
  core/src/lib.rs
  core/src/reward.rs
  miner/src/block_assembler.rs
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/module/chain.rs
  rpc/src/test.rs
  shared/src/shared.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/synchronizer.rs
  sync/src/tests/util.rs
  traits/src/chain_provider.rs
  util/jsonrpc-types/src/blockchain.rs
  util/jsonrpc-types/src/lib.rs
  util/reward-calculator/src/lib.rs
  verification/src/contextual_block_verifier.rs
Labels: hotfix, urgent

#1299 chore(deps): bump crossbeam-epoch from 0.7.1 to 0.7.2
  Cargo.lock
Labels: backport rc/v0.17, dependencies, m:security, s:ready-to-merge, urgent

#1306 fix: network continuely retry dialing on failed address
  network/src/peer_store/sqlite/peer_store.rs
  network/src/tests/sqlite_peer_store.rs
Labels: s:ready-to-merge

#1313 fix: tx pool config typo and new config param
  resource/ckb.toml
  shared/src/shared.rs
  shared/src/tx_pool/pool.rs
  shared/src/tx_pool/types.rs
Labels: s:ready-to-merge

#1309 fix: Preserve script hash type when converting to/from witness
  core/src/script.rs
  docs/hashes.toml
  resource/specs/testnet.toml
  rpc/README.md
  rpc/json/rpc.json
  test/src/specs/mining/size_limit.rs
Labels: s:ready-to-merge

#1312 feat: Upgrade CKB VM to 0.15.1
  Cargo.lock
  script/Cargo.toml
  script/src/syscalls/debugger.rs
  script/src/syscalls/load_cell.rs
  script/src/syscalls/load_code.rs
  script/src/syscalls/load_header.rs
  script/src/syscalls/load_input.rs
  script/src/syscalls/load_witness.rs
  script/src/syscalls/mod.rs
  script/src/syscalls/utils.rs
  script/src/verify.rs
Labels: s:ready-to-merge

#1252 feat: uncle descendant limit
  Cargo.lock
  chain/src/chain.rs
  core/src/uncle.rs
  miner/src/block_assembler.rs
  miner/src/candidate_uncles.rs
  miner/src/lib.rs
  notify/src/lib.rs
  shared/src/error.rs
  verification/Cargo.toml
  verification/src/contextual_block_verifier.rs
  verification/src/error.rs
  verification/src/tests/uncle_verifier.rs
  verification/src/uncles_verifier.rs
Labels: b:consensus, breaking change, m:consensus, m:security, s:ready-to-merge, s:waiting-on-reviewers

#1288 chore: ignore generated files in pre-commit hook
  devtools/git/pre-commit
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1286 refactor: use block_hash
  protocol/src/builder.rs
  protocol/src/protocol.fbs
  protocol/src/protocol_generated.rs
  protocol/src/protocol_generated_verifier.rs
  sync/src/relayer/block_proposal_process.rs
  sync/src/relayer/compact_block.rs
  sync/src/relayer/get_block_proposal_process.rs
  sync/src/relayer/mod.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1314 fix: randomly failed integration test valid since
  test/src/specs/tx_pool/valid_since.rs
Labels: s:ready-to-merge

#1316 feat: Specify hash type in block assembler config
  Cargo.lock
  ckb-bin/Cargo.toml
  ckb-bin/src/subcommand/cli/secp256k1_lock.rs
  ckb-bin/src/subcommand/init.rs
  miner/src/block_assembler.rs
  miner/src/config.rs
  test/src/node.rs
  test/src/specs/mining/bootstrap.rs
  util/app-config/Cargo.toml
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/lib.rs
Labels: s:ready-to-merge

#1317 fix: fix get peers rpc version field
  ckb-bin/src/subcommand/run.rs
  network/src/network.rs
  network/src/peer.rs
  network/src/protocols/identify.rs
  network/src/protocols/test.rs
  protocol/src/protocol.fbs
  protocol/src/protocol_generated.rs
  protocol/src/protocol_generated_verifier.rs
  rpc/src/test.rs
  test/src/net.rs
Labels: breaking change, s:ready-to-merge

#1318 fix: only accept blocks with a height greater than tip - N
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/error.rs
  sync/src/relayer/tests/compact_block_process.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1308 refactor: using ProposalShortId in CompactBlock
  Cargo.lock
  protocol/Cargo.toml
  protocol/src/builder.rs
  protocol/src/lib.rs
  protocol/src/protocol.fbs
  protocol/src/protocol_generated.rs
  protocol/src/protocol_generated_verifier.rs
  shared/src/tx_pool/pool.rs
  sync/src/relayer/block_transactions_verifier.rs
  sync/src/relayer/compact_block.rs
  sync/src/relayer/compact_block_verifier.rs
  sync/src/relayer/error.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/block_transactions_verifier.rs
  sync/src/relayer/tests/compact_block.rs
  sync/src/relayer/tests/compact_block_verifier.rs
  sync/src/relayer/tests/reconstruct_block.rs
Labels: b:p2p, breaking change, s:ready-to-merge

#1298 ci: speed up ci
  .travis.yml
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1324 chore: upgrade crossbeam channel
  Cargo.lock
  chain/src/chain.rs
  miner/src/block_assembler.rs
  miner/src/miner.rs
  notify/src/lib.rs
Labels: s:ready-to-merge

#1305 fix: ibd only with protect/whitelist peers
  sync/src/synchronizer/headers_process.rs
  sync/src/types.rs
  test/src/specs/sync/ibd_process.rs
Labels: s:ready-to-merge
