Repository nervosnetwork/ckb, pull requests merged in 2019-05, with the labels that each got.

#650 chore: export build_tx
  script/src/lib.rs
Labels: s:waiting-on-ci

#653 feat: add rpc experiment module
  resource/ckb.toml
  rpc/README.md
  rpc/src/config.rs
  rpc/src/module/experiment.rs
  rpc/src/module/mod.rs
  rpc/src/server.rs
  shared/src/chain_state.rs
  verification/src/lib.rs
Labels: s:waiting-on-author

#720 feat: move DryRuResult into jsonrpc-types
  rpc/src/module/experiment.rs
  test/src/node.rs
  test/src/rpc.rs
  test/src/specs/mining/size_limit.rs
  test/src/specs/sync/block_sync.rs
  test/src/specs/tx_pool/valid_since.rs
  util/jsonrpc-types/src/experiment.rs
  util/jsonrpc-types/src/lib.rs
Labels: s:waiting-on-author

#728 chore: lock parking_lot version
  Cargo.lock
  util/Cargo.toml
  util/logger/Cargo.toml
  util/stop-handler/Cargo.toml
Labels: s:waiting-on-ci

#714 feat: enforce resolve txs order within block
  chain/src/chain.rs
  core/src/cell.rs
  shared/src/chain_state.rs
Labels: s:waiting-on-reviewers

#753 fix: genesis epoch remainder reward
  spec/src/lib.rs
Labels: breaking change

#739 fix: next epoch calculate off-by-one
  core/src/extras.rs
  shared/src/shared.rs
  spec/src/consensus.rs
  sync/src/types.rs
Labels: breaking change

#757 chore: tweak max proposals limit 3000
  spec/src/consensus.rs
Labels: breaking change

#745 feat: genesis block customization
  benches/benches/process_block.rs
  core/src/script.rs
  docs/configure.md
  docs/hashes.toml
  resource/ckb.toml
  resource/specs/dev.toml
  resource/specs/testnet.toml
  resource/src/lib.rs
  script/testdata/always_success
  spec/src/lib.rs
  src/subcommand/cli/hashes.rs
  test/Cargo.toml
  test/integration.toml
  test/src/node.rs
  test/src/specs/mod.rs
  test/src/specs/relay/compact_block.rs
  test/src/specs/tx_pool/cellbase_maturity.rs
  util/app-config/src/lib.rs
  util/test-chain-utils/src/lib.rs
  verification/src/block_verifier.rs
  verification/src/tests/block_verifier.rs
Labels: breaking change

#758 [ᚬrc/v0.12.0] fix: fix NervosDAO calculation logic
  chain/src/chain.rs
  store/src/store.rs
  util/dao/src/lib.rs
Labels: hotfix

#760 docs: update rpc doc
  rpc/README.md
  rpc/json/rpc.json
Labels: s:waiting-on-author

#767 [ᚬrc/v0.12.0] perf: avoiding duplicate block downloading
  sync/src/synchronizer/mod.rs
Labels: hotfix

#766 [ᚬrc/v0.12.0] perf: change db cache to store cache
  Cargo.lock
  benches/benches/process_block.rs
  resource/ckb.toml
  script/src/verify.rs
  shared/src/shared.rs
  src/subcommand/export.rs
  src/subcommand/import.rs
  src/subcommand/prof.rs
  src/subcommand/run.rs
  store/Cargo.toml
  store/src/lib.rs
  store/src/store.rs
  util/app-config/Cargo.toml
  util/app-config/src/app_config.rs
Labels: hotfix

#762 feat: Live cell block hash
  Makefile
  devtools/ci/script.sh
  devtools/doc/rpc.py
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/module/chain.rs
Labels: breaking change

#772 [ᚬrc/v0.12.0] feat: prof support start from non-zero block
  src/subcommand/prof.rs
Labels: hotfix

#769 [ᚬrc/v0.12.0] chore: bump rust-toolchain to 1.34.2
  .travis.yml
  docker/hub/Dockerfile
  docs/get-ckb.md
  rust-toolchain
Labels: hotfix

#776 [ᚬrc/v0.12.0] fix(deps): Upgrade p2p fix gracefully shutdown network service
  Cargo.lock
  network/Cargo.toml
Labels: hotfix

#774 [ᚬrylai-testbed] feat: tweak max block cycles limit
  resource/specs/dev.toml
  resource/specs/testnet.toml
  spec/src/consensus.rs
  test/integration.toml
Labels: breaking change

#780 [ᚬrc/v0.12.0] chore: use UTC time in version info
  util/build-info/src/lib.rs
Labels: hotfix

#783 [ᚬrylai-testbed] perf: delay acquire chain_state lock until tried cache
  miner/src/block_assembler.rs
  shared/src/shared.rs
Labels: hotfix

#788 [ᚬrc/v0.12.0] fix: correct block_median_count
  traits/src/block_median_time_context.rs
Labels: hotfix

#791 [ᚬrylai-testbed-3] feat: upgrade CKB VM to W^X version
  Cargo.lock
  script/Cargo.toml
  script/src/verify.rs
Labels: breaking change

#781 [ᚬrc/v0.12.0] feat: add secp256k1 in dev chainspec
  docs/hashes.toml
  resource/specs/dev.toml
Labels: hotfix

#790 [ᚬrc/v0.12.0] chore: update script used to generate CHANGELOG
  .gitignore
  devtools/git/github-changelog.py
Labels: hotfix

#792 [ᚬrc/v0.12.0] chore: print warning about default miner key
  src/subcommand/init.rs
Labels: hotfix

#793 [ᚬrc/v0.12.0] fix: Outbound peer service and discovery service
  network/src/config.rs
  network/src/network.rs
  network/src/protocols/discovery.rs
  network/src/services/outbound_peer.rs
  test/src/net.rs
  test/src/specs/mod.rs
Labels: hotfix

#789 [ᚬrc/v0.12.0] doc: Group rpc APIs [skip ci]
  devtools/doc/rpc.py
  rpc/README.md
  rpc/json/rpc.json
Labels: hotfix

#797 [ᚬrc/v0.12.0] fix(network): Avoid dial too often
  network/src/network.rs
  network/src/services/outbound_peer.rs
Labels: hotfix

#801 [ᚬrc/v0.12.0] docs: tweak RPC doc markdown style.
  devtools/doc/rpc.py
  rpc/README.md
  rpc/json/rpc.json
Labels: hotfix

#803 [ᚬrc/v0.12.0] chore: upgrade p2p
  Cargo.lock
  network/Cargo.toml
Labels: hotfix

#808 [ᚬrc/v0.12.0] docs: no rustup override in docs
  docs/get-ckb.md
Labels: hotfix

#809 [ᚬrc/v0.12.0] chore: remove unnecessary code
  rpc/src/module/chain.rs
  rpc/src/module/experiment.rs
  rpc/src/module/miner.rs
  rpc/src/module/pool.rs
  rpc/src/module/test.rs
  store/src/store.rs
  util/jsonrpc-types/src/block_template.rs
  util/jsonrpc-types/src/blockchain.rs
  util/jsonrpc-types/src/proposal_short_id.rs
Labels: hotfix

#811 [ᚬrc/v0.12.0] feat: upgrade CKB VM to latest version with performance improvements
  Cargo.lock
  script/Cargo.toml
Labels: hotfix

#815 [ᚬrc/v0.12.0] fix: Change dns seed record hash function to blake2b_256
  network/src/services/dns_seeding/seed_record.rs
Labels: hotfix

#814 [ᚬrc/v0.12.0] chore: rpc bind localhost in default config
  resource/ckb.toml
  util/app-config/src/app_config.rs
Labels: hotfix

#819 [ᚬrc/v0.12.0] fix: load_script_hash should use script's own hash for lock script
  core/src/script.rs
  script/src/syscalls/mod.rs
  script/src/verify.rs
Labels: breaking change, hotfix

#818 [ᚬrc/v0.12.0] chore(ci): use xenial in travis
  .travis.yml
Labels: hotfix

#822 [ᚬrc/v0.12.0] feat: add load witness syscall
  script/src/syscalls/load_witness.rs
  script/src/syscalls/mod.rs
  script/src/verify.rs
Labels: breaking change, hotfix

#820 [ᚬrc/v0.12.0] fix: proposal duplidate
  miner/src/block_assembler.rs
  shared/src/chain_state.rs
  shared/src/tx_pool/pool.rs
Labels: hotfix

#821 [ᚬrc/v0.12.0] chore(docker): build docker image from nervos/ckb-docker-builder
  docker/hub/Dockerfile
  docs/run-ckb-with-docker.md
Labels: hotfix

#823 [ᚬrc/v0.12.0] chore: Remove DNS seeding public key
  network/src/services/dns_seeding/mod.rs
Labels: hotfix

#824 [ᚬrc/v0.12.0] chore: upgrade p2p
  Cargo.lock
  network/Cargo.toml
Labels: hotfix

#825 [ᚬrylai] fix: Filter out p2p field in address
  network/src/peer_store.rs
  network/src/peer_store/sqlite/db.rs
  network/src/peer_store/sqlite/peer_store.rs
  network/src/protocols/discovery.rs
Labels: hotfix

#826 [ᚬrylai] fix: ban peer deadlock
  network/src/network.rs
Labels: hotfix

#850 fix: ensure EBREAK has proper cycle set
  rpc/README.md
  rpc/json/rpc.json
  script/src/cost_model.rs
  script/src/syscalls/debugger.rs
  script/src/syscalls/load_cell.rs
  script/src/syscalls/load_header.rs
  script/src/syscalls/load_input.rs
  script/src/syscalls/load_script_hash.rs
  script/src/syscalls/load_tx_hash.rs
  script/src/syscalls/load_witness.rs
  shared/tx-pool-executor/src/tx_pool_executor.rs
Labels: b:consensus, breaking change

#851 [ᚬrylai] chore: more pretty log output
  chain/src/chain.rs
  network/src/network.rs
  sync/src/synchronizer/get_headers_process.rs
  sync/src/synchronizer/headers_process.rs
Labels: hotfix

#841 feat: apply tx_pool limit
  miner/src/block_assembler.rs
  resource/ckb.toml
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/module/experiment.rs
  rpc/src/module/pool.rs
  shared/src/chain_state.rs
  shared/src/tx_pool/orphan.rs
  shared/src/tx_pool/pending.rs
  shared/src/tx_pool/pool.rs
  shared/src/tx_pool/proposed.rs
  shared/src/tx_pool/types.rs
  shared/tx-pool-executor/src/tx_pool_executor.rs
  src/subcommand/prof.rs
  test/src/main.rs
  test/src/node.rs
  test/src/rpc.rs
  test/src/specs/tx_pool/limit.rs
  test/src/specs/tx_pool/mod.rs
  util/jsonrpc-types/src/pool.rs
  verification/src/contextual_block_verifier.rs
  verification/src/error.rs
  verification/src/transaction_verifier.rs
Labels: b:cli, b:rpc, breaking change

#873 chore: rename the target in log for rpc module
  resource/ckb-miner.toml
  resource/ckb.toml
  rpc/src/module/experiment.rs
  rpc/src/module/miner.rs
  rpc/src/module/pool.rs
  rpc/src/module/test.rs
Labels: s:waiting-on-ci

#886 fix: integration test cycle calc
  rpc/README.md
  rpc/json/rpc.json
  test/src/specs/tx_pool/limit.rs
Labels: hotfix

#881 chore: improve build time
  Cargo.lock
  Cargo.toml
  build.rs
  ckb-bin/Cargo.toml
  ckb-bin/src/helper.rs
  ckb-bin/src/lib.rs
  ckb-bin/src/subcommand/cli/blake.rs
  ckb-bin/src/subcommand/cli/hashes.rs
  ckb-bin/src/subcommand/cli/mod.rs
  ckb-bin/src/subcommand/cli/secp256k1_lock.rs
  ckb-bin/src/subcommand/export.rs
  ckb-bin/src/subcommand/import.rs
  ckb-bin/src/subcommand/init.rs
  ckb-bin/src/subcommand/miner.rs
  ckb-bin/src/subcommand/mod.rs
  ckb-bin/src/subcommand/prof.rs
  ckb-bin/src/subcommand/run.rs
  devtools/ci/script.sh
  src/main.rs
Labels: s:waiting-on-ci

#890 feat: revise remainder reward rule
  chain/src/tests/basic.rs
  core/src/extras.rs
  util/dao/src/lib.rs
Labels: b:consensus, breaking change

#876 feat: tweak consensus params
  chain/src/tests/basic.rs
  chain/src/tests/util.rs
  resource/specs/dev.toml
  resource/specs/testnet.toml
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/test.rs
  spec/src/consensus.rs
Labels: b:consensus, breaking change, p:must-have

#889 feat: add codename in version
  Makefile
  docs/hashes.toml
  resource/specs/testnet.toml
  src/main.rs
  util/build-info/src/lib.rs
Labels: breaking change

#859 feat: Use snappy to compress large messages
  Cargo.lock
  network/Cargo.toml
  network/src/compress.rs
  network/src/lib.rs
  network/src/protocols/mod.rs
Labels: b:p2p, breaking change, s:waiting-on-reviewers

#878 fix: calculate the current median time from tip
  test/src/main.rs
  test/src/specs/tx_pool/valid_since.rs
  test/src/utils.rs
  traits/src/block_median_time_context.rs
  verification/src/transaction_verifier.rs
Labels: breaking change

#845 feat: limit TXO set memory usage
  chain/src/chain.rs
  core/src/transaction.rs
  core/src/transaction_meta.rs
  db/src/cachedb.rs
  db/src/lib.rs
  db/src/memorydb.rs
  db/src/rocksdb.rs
  rpc/src/module/chain.rs
  shared/src/cell_set.rs
  shared/src/chain_state.rs
  store/src/lib.rs
  store/src/store.rs
Labels: b:database, breaking change

#874 feat: revise uncle rule
  Cargo.lock
  chain/Cargo.toml
  chain/src/chain.rs
  core/src/uncle.rs
  db/Cargo.toml
  miner/Cargo.toml
  miner/src/block_assembler.rs
  shared/Cargo.toml
  shared/src/chain_state.rs
  spec/src/consensus.rs
  store/Cargo.toml
  store/src/lib.rs
  store/src/store.rs
  sync/Cargo.toml
  traits/Cargo.toml
  util/app-config/Cargo.toml
  util/jsonrpc-types/Cargo.toml
  verification/Cargo.toml
  verification/src/contextual_block_verifier.rs
  verification/src/error.rs
  verification/src/lib.rs
  verification/src/tests/uncle_verifier.rs
  verification/src/transaction_verifier.rs
  verification/src/uncles_verifier.rs
Labels: b:consensus, b:database, breaking change, p:must-have

#920 feat: tweak consensus params
  spec/src/consensus.rs
Labels: b:consensus, m:consensus

#923 [ᚬrc/v0.13.0] fix: Sync blocked by protected peer
  sync/src/synchronizer/mod.rs
Labels: hotfix

#925 [ᚬrc/v0.13.0] fix: cuckoo cycle max edge verification
  pow/src/cuckoo.rs
Labels: hotfix
