Repository nervosnetwork/ckb, pull requests merged in 2019-10, with the labels that each got.

#1677 fix: fix init args
  ckb-bin/src/subcommand/init.rs
Labels: backport rc/v0.22

#1681 [ᚬrc/v0.22] feat: Allow setting the spec file in ckb init.
  Cargo.lock
  ckb-bin/Cargo.toml
  ckb-bin/src/subcommand/init.rs
  resource/ckb-miner.toml
  resource/ckb.toml
  resource/src/lib.rs
  resource/src/template.rs
  spec/src/lib.rs
  util/app-config/src/app_config.rs
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/lib.rs
Labels: hotfix

#1678 [ᚬrc/v0.22] fix: get_block_transactions_process should fill missing uncle in resp…
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/get_block_transactions_process.rs
Labels: hotfix

#1605 test: Add cases about proposed/committed rewards
  test/src/lib.rs
  test/src/main.rs
  test/src/node.rs
  test/src/rpc.rs
  test/src/specs/alert/mod.rs
  test/src/specs/indexer/mod.rs
  test/src/specs/mining/fee.rs
  test/src/specs/mining/mod.rs
  test/src/specs/p2p/mod.rs
  test/src/specs/relay/mod.rs
  test/src/specs/sync/chain_forks.rs
  test/src/specs/sync/mod.rs
  test/src/specs/tx_pool/mod.rs
  test/src/txo.rs
  test/src/utils.rs
Labels: s:waiting-on-author, s:waiting-on-reviewers

#1684 fix(test): First 11 cellbases have not outputs
  test/src/specs/sync/chain_forks.rs
  test/src/utils.rs
Labels: s:ready-to-merge

#1668 test: transaction since overflow
  verification/src/tests/transaction_verifier.rs
Labels: s:ready-to-merge

#1663 chore: typo
  chain/src/tests/basic.rs
  chain/src/tests/delay_verify.rs
Labels: s:ready-to-merge

#1685 fix: fix construct_uncle in integration test
  test/src/node.rs
  test/src/specs/mining/uncle.rs
  test/src/specs/sync/chain_forks.rs
Labels: s:ready-to-merge

#1669 chore(test): Allow CI debug logs
  test/src/node.rs
Labels: s:ready-to-merge

#1693 test: simple header field json format check
  Cargo.lock
  util/jsonrpc-types/Cargo.toml
  util/jsonrpc-types/src/blockchain.rs
Labels: s:ready-to-merge

#1696 fix: set `next_epoch_diff` to one instead of panic when it is zero
  spec/src/consensus.rs
Labels: s:ready-to-merge

#1690 ci: Make sure cargo-audit up-to-date
  .travis.yml
  Makefile
Labels: s:ready-to-merge

#1691 chore: speed up maturity test
  test/src/specs/tx_pool/reference_header_maturity.rs
Labels: s:ready-to-merge

#1689 chore: issuance comment
  spec/src/consensus.rs
Labels: s:ready-to-merge

#1664 chore: update get_block_template rpc doc
  rpc/README.md
  rpc/json/rpc.json
Labels: s:ready-to-merge

#1673 docs: Update PoW mining algorithm description
  README.md
Labels: s:ready-to-merge

#1700 fix: fix panic when submit tx with low fee rate
  error/src/lib.rs
  tx-pool/src/error.rs
Labels: s:ready-to-merge

#1682 feat: Allow setting the spec file in ckb init.
  Cargo.lock
  ckb-bin/Cargo.toml
  ckb-bin/src/subcommand/init.rs
  resource/ckb-miner.toml
  resource/ckb.toml
  resource/src/lib.rs
  resource/src/template.rs
  spec/src/lib.rs
  util/app-config/src/app_config.rs
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/lib.rs
Labels: s:ready-to-merge

#1707 fix: resolve uncles hash calculation issue
  util/types/src/extension/calc_hash.rs
Labels: breaking change, s:ready-to-merge

#1640 test: move typical_secp256k1_blake160_2_in_2_out cycle and size test
  Cargo.lock
  script/Cargo.toml
  script/src/verify.rs
  spec/src/consensus.rs
  test/src/specs/tx_pool/send_secp_tx.rs
  util/test-chain-utils/Cargo.toml
  util/test-chain-utils/src/chain.rs
  util/test-chain-utils/src/lib.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1702 test: fix compact_block_missing_fresh_txs integration test
  test/src/net.rs
  test/src/specs/p2p/malformed_message.rs
  test/src/specs/relay/compact_block.rs
  test/src/specs/relay/get_block_transactions_process.rs
  test/src/specs/sync/block_sync.rs
Labels: backport rc/v0.22, s:ready-to-merge, s:waiting-on-reviewers

#1701 feat: zeroize when privkey dropped
  util/crypto/src/secp/mod.rs
  util/crypto/src/secp/privkey.rs
Labels: s:ready-to-merge

#1515 refactor: change enum from `[byte; 1]` to `byte`
  benches/benches/benchmarks/overall.rs
  benches/benches/benchmarks/util.rs
  chain/src/tests/reward.rs
  indexer/src/store.rs
  script/src/syscalls/mod.rs
  script/src/verify.rs
  spec/src/lib.rs
  test/src/node.rs
  test/src/specs/dao/mod.rs
  test/src/specs/dao/satoshi_dao_occupied.rs
  test/src/specs/indexer/genesis_issued_cells.rs
  test/src/specs/mining/bootstrap.rs
  test/src/specs/tx_pool/send_secp_tx.rs
  tx-pool/src/component/proposed.rs
  tx-pool/src/process/block_template.rs
  util/dao/src/lib.rs
  util/jsonrpc-types/src/blockchain.rs
  util/test-chain-utils/src/chain.rs
  util/types/schemas/ckb.mol
  util/types/src/conversion/blockchain.rs
  util/types/src/core/blockchain.rs
  util/types/src/core/cell.rs
  util/types/src/extension/check_data.rs
  util/types/src/generated/types.rs
  verification/src/transaction_verifier.rs
Labels: s:ready-to-merge, s:waiting-on-author

#1712 fix: fix tx_pool_info
  test/src/specs/indexer/basic.rs
  tx-pool/src/component/orphan.rs
  tx-pool/src/pool.rs
Labels: backport rc/v0.23, s:ready-to-merge, s:waiting-on-reviewers

#1711 feat: enable ansi support for windows
  Cargo.lock
  util/logger/Cargo.toml
  util/logger/src/lib.rs
Labels: s:ready-to-merge

#1697 fix: Fix get_header_view panic bug
  sync/src/types.rs
Labels: backport rc/v0.22, s:ready-to-merge

#1720 feat: Add load transaction syscall
  script/src/syscalls/load_tx.rs
  script/src/syscalls/load_tx_hash.rs
  script/src/syscalls/mod.rs
  script/src/verify.rs
Labels: s:ready-to-merge

#1725 test: Comment IBD cases
  test/src/main.rs
Labels: s:ready-to-merge

#1709 fix(test): skip the panicked checking for rest nodes
  test/src/main.rs
Labels: s:ready-to-merge

#1727 ci(Azure): use maximum timeout for integration test job
  azure-pipelines.yml
Labels: s:ready-to-merge

#1714 fix: tx sorted_keys order by relation
  test/src/specs/indexer/basic.rs
  tx-pool/src/component/container.rs
  tx-pool/src/component/pending.rs
  tx-pool/src/component/proposed.rs
  tx-pool/src/process/chain_reorg.rs
Labels: backport rc/v0.23, s:ready-to-merge, t:bug

#1730 feat: Upgrade CKB VM to 0.18.0
  Cargo.lock
  script/Cargo.toml
Labels: s:ready-to-merge

#1741 fix: Overflow panic in load_cell_data_as_code syscall
  script/src/syscalls/load_cell_data.rs
  script/src/syscalls/mod.rs
Labels: s:ready-to-merge

#1659 feat: Fee estimate RPC
  Cargo.lock
  Cargo.toml
  benches/benches/benchmarks/overall.rs
  rpc/Cargo.toml
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/module/experiment.rs
  rpc/src/module/pool.rs
  rpc/src/service_builder.rs
  rpc/src/test.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/helper.rs
  test/src/main.rs
  test/src/rpc.rs
  test/src/specs/mod.rs
  test/src/specs/relay/transaction_relay_low_fee_rate.rs
  test/src/specs/tx_pool/fee_estimate.rs
  test/src/specs/tx_pool/limit.rs
  test/src/specs/tx_pool/mod.rs
  test/src/specs/tx_pool/send_low_fee_rate_tx.rs
  tx-pool/Cargo.toml
  tx-pool/src/component/commit_txs_scanner.rs
  tx-pool/src/component/pending.rs
  tx-pool/src/config.rs
  tx-pool/src/lib.rs
  tx-pool/src/pool.rs
  tx-pool/src/process/chain_reorg.rs
  tx-pool/src/process/estimate_fee_rate.rs
  tx-pool/src/process/estimator_process_block.rs
  tx-pool/src/process/estimator_track_tx.rs
  tx-pool/src/process/mod.rs
  tx-pool/src/process/submit_txs.rs
  tx-pool/src/service.rs
  util/fee-estimator/Cargo.toml
  util/fee-estimator/src/estimator.rs
  util/fee-estimator/src/fee_rate.rs
  util/fee-estimator/src/lib.rs
  util/fee-estimator/src/tx_confirm_stat.rs
  util/jsonrpc-types/src/experiment.rs
  util/jsonrpc-types/src/lib.rs
  util/jsonrpc-types/src/primitive.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1705 feat: verify genesis block specific rules on start
  Cargo.lock
  ckb-bin/src/subcommand/run.rs
  indexer/src/store.rs
  spec/src/consensus.rs
  spec/src/lib.rs
  util/dao/utils/src/lib.rs
  verification/Cargo.toml
  verification/src/error.rs
  verification/src/genesis_verifier.rs
  verification/src/lib.rs
  verification/src/tests/genesis_verifier.rs
  verification/src/tests/mod.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1754 chore: display epoch in terminal and log files
  chain/src/chain.rs
  util/types/src/core/extras.rs
Labels: s:ready-to-merge

#1751 chore: do not output stack backtrace if failed to validate the tx
  script/src/verify.rs
Labels: s:ready-to-merge

#1755 chore: typo of epochs
  script/src/syscalls/mod.rs
Labels: s:ready-to-merge

#1742 fix: ignore fork branch when get_cellbase_output_capacity_details, get_header and get_block rpc
  rpc/src/module/chain.rs
  rpc/src/module/test.rs
  store/src/store.rs
  test/src/rpc.rs
  test/src/specs/sync/invalid_block.rs
Labels: backport rc/v0.23, s:ready-to-merge

#1750 chore: upgrade p2p dep
  Cargo.lock
  network/Cargo.toml
  network/src/network.rs
Labels: breaking change, s:ready-to-merge, s:waiting-on-reviewers

#1732 refactor: support run integration tests concurrently
  .travis.yml
  Makefile
  test/src/lib.rs
  test/src/main.rs
  test/src/utils.rs
  test/src/worker.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1735 feat: Expose methods to tweak CKB VM with CKB runtime outside CKB
  script/Cargo.toml
  script/build.rs
  script/src/syscalls/debugger.rs
  script/src/verify.rs
Labels: s:ready-to-merge

#1759 test: add some debug info on valid_since test
  test/src/specs/tx_pool/valid_since.rs
Labels: s:ready-to-merge

#1753 chore: permanent difficulty for dummy mode
  pow/src/lib.rs
  resource/specs/dev.toml
  spec/src/consensus.rs
  spec/src/lib.rs
Labels: s:ready-to-merge

#1761 fix: fix valid since test
  test/src/specs/tx_pool/valid_since.rs
Labels: backport rc/v0.23

#1756 fix: fix benchmark overflow
  rpc/README.md
  rpc/json/rpc.json
  util/dao/utils/src/lib.rs
Labels: s:ready-to-merge

#1734 chore(deps): bump bitflags, failure, faster-hex, libc, proc-macro-hack and backtrace
  Cargo.lock
Labels: dependencies, s:ready-to-merge

#1757 feat: shutdown when protocol handle panic
  ckb-bin/src/helper.rs
  ckb-bin/src/subcommand/run.rs
  network/src/network.rs
  network/src/protocols/test.rs
  rpc/src/test.rs
  test/src/net.rs
Labels: s:ready-to-merge

#1766 chore: tweak block size limit
  spec/src/consensus.rs
Labels: s:ready-to-merge

#1765 fix: avoids creating tmp folder for db initialization
  shared/src/shared.rs
Labels: s:ready-to-merge

#1771 chore: cleanup outdated code
  sync/src/synchronizer/headers_process.rs
Labels: s:ready-to-merge

#1768 style: Unified protocol handshake information format
  network/src/network.rs
  network/src/protocols/mod.rs
Labels: breaking change, s:ready-to-merge

#1777 fix: Expose CellDep fields
  util/jsonrpc-types/src/blockchain.rs
Labels: s:ready-to-merge

#1778 chore: use ckb-system-scripts v0.4.0
  Cargo.lock
  benches/Cargo.toml
  resource/Cargo.toml
Labels: dependencies, s:ready-to-merge

#1772 fix: Limit p2p protocol message size
  ckb-bin/src/subcommand/run.rs
  network/src/lib.rs
  network/src/network.rs
  network/src/protocols/mod.rs
  network/src/protocols/test.rs
  test/src/net.rs
Labels: s:ready-to-merge
