Repository nervosnetwork/ckb, pull requests merged in 2019-08, with the labels that each got.

#1329 feat: Allow dep and input in same tx use same previous output
  core/src/cell.rs
Labels: s:ready-to-merge

#1328 fix: `get_cell_data` should use cache
  benches/Cargo.toml
  benches/benches/fetch_cell_output.rs
  resource/ckb.toml
  store/src/store.rs
Labels: s:ready-to-merge

#1326 perf: add committed txs cache for compact block reconstruction
  resource/ckb.toml
  shared/src/chain_state.rs
  shared/src/tx_pool/pool.rs
  shared/src/tx_pool/types.rs
  sync/src/relayer/get_block_proposal_process.rs
  sync/src/relayer/mod.rs
Labels: s:bench-needed, s:ready-to-merge

#1338 chore: clean DaoStats
  protos/schemas/common.fbs
  protos/src/generated/common.rs
Labels: b:database, breaking change, s:ready-to-merge

#1337 fix: process block bench
  Cargo.lock
  benches/Cargo.toml
  benches/benches/process_block.rs
Labels: s:ready-to-merge, urgent

#1339 chore: upgrade cryptography library
  Cargo.lock
  network/Cargo.toml
  network/src/services/dns_seeding/seed_record.rs
  util/crypto/Cargo.toml
  util/crypto/src/secp/signature.rs
Labels: s:ready-to-merge

#1343 chore: tweak cellbase maturity
  resource/specs/testnet.toml
  spec/src/consensus.rs
Labels: b:consensus, breaking change, m:consensus, s:ready-to-merge

#1347 chore: Expose ScriptHashType in RPC module
  util/jsonrpc-types/src/lib.rs
Labels: s:ready-to-merge

#1307 feat: difficulty adjustment rfc version
  .gitignore
  Cargo.lock
  Cargo.toml
  chain/src/tests/basic.rs
  core/src/extras.rs
  protos/schemas/common.fbs
  protos/src/convert/from_common.rs
  protos/src/convert/to_common.rs
  protos/src/generated/common.rs
  rpc/README.md
  rpc/json/rpc.json
  spec/Cargo.toml
  spec/src/consensus.rs
  spec/src/lib.rs
  util/dao/src/lib.rs
  util/rational/Cargo.toml
  util/rational/src/lib.rs
  verification/src/tests/uncle_verifier.rs
Labels: b:consensus, b:database, breaking change, m:consensus, s:ready-to-merge

#1351 [ᚬrc/v0.17] feat: difficulty adjustment rfc version
  .gitignore
  Cargo.lock
  Cargo.toml
  chain/src/tests/basic.rs
  core/src/extras.rs
  protos/schemas/common.fbs
  protos/src/convert/from_common.rs
  protos/src/convert/to_common.rs
  protos/src/generated/common.rs
  rpc/README.md
  rpc/json/rpc.json
  spec/Cargo.toml
  spec/src/consensus.rs
  spec/src/lib.rs
  util/dao/src/lib.rs
  util/rational/Cargo.toml
  util/rational/src/lib.rs
  verification/src/tests/uncle_verifier.rs
Labels: hotfix

#1358 [ᚬrc/v0.18] feat: add 10x faster miner
  Cargo.lock
  miner/Cargo.toml
  miner/build.rs
  miner/src/worker/cuckoo.c
  miner/src/worker/cuckoo_simple.rs
  miner/src/worker/portable_endian.h
Labels: hotfix

#1341 feat: Implement cell's type ID special script
  script/src/lib.rs
  script/src/type_id.rs
  script/src/verify.rs
Labels: s:ready-to-merge

#1128 perf: add more cache in store to speed up reward calculation
  resource/ckb.toml
  store/src/config.rs
  store/src/lib.rs
  store/src/store.rs
  sync/src/tests/synchronizer.rs
Labels: s:ready-to-merge

#1357 chore: use minimal cache in Travis CI
  .travis.yml
Labels: s:ready-to-merge

#1366 [ᚬrc/v0.18] fix: orphan_rate_estimation panic at div zero
  spec/src/consensus.rs
  util/rational/src/lib.rs
  util/rational/src/tests.rs
Labels: backport rc/v0.18, hotfix

#1350 test: Simplify dao tests
  test/src/specs/tx_pool/dao.rs
Labels: s:ready-to-merge

#1359 fix: Multiple type ID cell creation in single transaction
  script/src/type_id.rs
  script/src/verify.rs
Labels: s:ready-to-merge

#1360 chore: Expose Status type in jsonrpc-types module
  util/jsonrpc-types/src/lib.rs
Labels: s:ready-to-merge

#1370 [ᚬrc/v0.18] fix: cuckoo.c fails to compile in CentOS
  miner/src/worker/cuckoo.c
Labels: hotfix

#1372 [ᚬrc/v0.18] fix: header verifier with wrong header resolver
  miner/src/block_assembler.rs
  rpc/src/module/miner.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/types.rs
  verification/src/block_verifier.rs
Labels: hotfix

#1378 [ᚬrc/v0.18] chore: use minimal cache in Travis CI
  .travis.yml
Labels: hotfix

#1379 fix: Expose data field in jsonrpc-types' Witness
  util/jsonrpc-types/src/blockchain.rs
Labels: s:ready-to-merge

#1369 fix: cuckoo.c fails to compile in CentOS
  miner/src/worker/cuckoo.c
Labels: s:ready-to-merge

#1380 Twist transaction hashes log
  sync/src/relayer/transaction_hashes_process.rs
Labels: s:ready-to-merge

#1361 refactor: use `TransactionInfo` instead of `BlockInfo`
  chain/src/tests/basic.rs
  core/src/cell.rs
  core/src/extras.rs
  script/src/syscalls/mod.rs
  script/src/verify.rs
  store/src/store.rs
  util/test-chain-utils/src/median_time.rs
  verification/src/tests/transaction_verifier.rs
  verification/src/transaction_verifier.rs
Labels: s:ready-to-merge

#1383 feat: allow dns resolver on rpc server
  rpc/src/server.rs
Labels: s:ready-to-merge

#1385 feat(ckb-bin): add interactive mode for init sub command
  Cargo.lock
  ckb-bin/Cargo.toml
  ckb-bin/src/helper.rs
  ckb-bin/src/subcommand/init.rs
  db/src/db.rs
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/lib.rs
Labels: s:ready-to-merge

#1382 feat(ckb-bin): add reset data subcommand
  ckb-bin/src/helper.rs
  ckb-bin/src/lib.rs
  ckb-bin/src/subcommand/mod.rs
  ckb-bin/src/subcommand/reset_data.rs
  util/app-config/src/app_config.rs
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/lib.rs
Labels: s:ready-to-merge

#1392 chore: skip Travis on bors merge in develop
  .travis.yml
Labels: s:ready-to-merge

#1381 feat: Split load data logic from load code syscall
  script/src/syscalls/load_cell_data.rs
  script/src/syscalls/mod.rs
  script/src/syscalls/utils.rs
Labels: s:ready-to-merge

#1390 fix: Calculate transaction fees in order
  util/reward-calculator/src/lib.rs
Labels: backport rc/v0.18, s:ready-to-merge

#1397 fix: script debug fmt
  core/src/script.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1407 [ᚬrc/v0.18] fix: Calculate transaction fees in order
  util/reward-calculator/src/lib.rs
Labels: hotfix

#1411 [ᚬrc/v0.18] fix: header provider index check
  shared/src/chain_state.rs
Labels: hotfix

#1412 [ᚬrc/v0.18] feat: Hardcode allow 34827
  core/src/cell.rs
  verification/src/contextual_block_verifier.rs
Labels: hotfix

#1414 chore: remove block_hash from get_live_cell params
  rpc/README.md
  rpc/json/rpc.json
Labels: s:ready-to-merge

#1335 feat: tx_pool support sort by fee rate
  chain/src/chain.rs
  miner/src/block_assembler.rs
  rpc/src/module/chain.rs
  script/src/verify.rs
  shared/src/chain_state.rs
  shared/src/tx_pool.rs
  shared/src/tx_pool/commit_txs_scanner.rs
  shared/src/tx_pool/pending.rs
  shared/src/tx_pool/pool.rs
  shared/src/tx_pool/proposed.rs
  shared/src/tx_pool/types.rs
  shared/tx-pool-executor/src/tx_pool_executor.rs
  test/src/node.rs
  test/src/specs/mining/size_limit.rs
  util/dao/src/lib.rs
  util/types/src/core/cell.rs
  verification/src/tests/transaction_verifier.rs
Labels: s:ready-to-merge

#1410 chore: remove unnecessary lock
  Cargo.lock
  miner/Cargo.toml
  miner/src/lib.rs
  miner/src/miner.rs
  network/src/protocols/test.rs
Labels: s:ready-to-merge

#1433 chore: Correct typo block_assember to block_assembler
  docs/quick-start.md
  docs/run-ckb-with-docker.md
Labels: s:ready-to-merge

#1418 test: add randomness for uncle test
  Cargo.lock
  verification/Cargo.toml
  verification/src/tests/uncle_verifier.rs
Labels: s:ready-to-merge

#1439 chore: remove some useless code
  notify/src/lib.rs
  util/src/lib.rs
Labels: s:ready-to-merge

#1377 chore(deps): bump sentry from 0.15.5 to 0.16.0
  Cargo.lock
  network/Cargo.toml
  rpc/Cargo.toml
  sync/Cargo.toml
  util/app-config/Cargo.toml
Labels: dependencies, s:ready-to-merge, s:waiting-on-reviewers

#1443 chore: lock exact ckb-system-scripts version
  resource/Cargo.toml
Labels: s:ready-to-merge

#1442 fix: Use new serialization to calculate type_id (include since)
  script/src/type_id.rs
  script/src/verify.rs
  util/types/src/constants.rs
Labels: p:must-have, s:ready-to-merge

#1399 fix: check sync_started before handle InIBD
  sync/src/lib.rs
  sync/src/synchronizer/in_ibd_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/types.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1441 chore: use `std::{HashMap, HashSet}` instead of `fnv`
  Cargo.lock
  network/Cargo.toml
  network/src/network.rs
  network/src/peer.rs
  network/src/peer_registry.rs
  network/src/peer_store/sqlite/db_trace.rs
  network/src/peer_store/sqlite/peer_store.rs
  network/src/protocols/discovery.rs
  notify/Cargo.toml
  notify/src/lib.rs
  shared/src/tx_pool/orphan.rs
  shared/src/tx_pool_ext.rs
  sync/Cargo.toml
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/compact_block_process.rs
  sync/src/relayer/transactions_process.rs
  sync/src/synchronizer/block_pool.rs
  sync/src/tests/inflight_blocks.rs
  sync/src/types.rs
  util/Cargo.toml
  util/network-alert/Cargo.toml
  util/network-alert/src/alert_relayer.rs
  util/network-alert/src/notifier.rs
  util/network-alert/src/verifier.rs
  util/src/lib.rs
  util/src/linked_hash_set.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1368 chore: change `send_transaction` RPC from broadcasting tx to tx_hash
  ckb-bin/src/subcommand/run.rs
  rpc/src/module/pool.rs
  rpc/src/service_builder.rs
  rpc/src/test.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1444 Avoid block clone
  miner/src/client.rs
  miner/src/miner.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1437 test: make sure secp-tx is committed
  test/src/specs/tx_pool/send_secp_tx.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1447 chore: remove bech32
  Cargo.lock
  util/crypto/Cargo.toml
  util/crypto/src/bech32/error.rs
  util/crypto/src/bech32/mod.rs
  util/crypto/src/lib.rs
Labels: s:ready-to-merge

#1449 chore: clean code, not allow dead_code
  miner/src/candidate_uncles.rs
  miner/src/lib.rs
  network/src/peer_store/sqlite/db_trace.rs
  network/src/peer_store/sqlite/peer_store.rs
  network/src/protocols/identify.rs
  network/src/services/dns_seeding/seed_record.rs
  util/crypto/src/secp/mod.rs
  util/crypto/src/secp/signature.rs
Labels: s:ready-to-merge

#1455 fix: remove the block_ext cache
  resource/ckb.toml
  store/src/config.rs
  store/src/lib.rs
  store/src/store.rs
Labels: s:ready-to-merge

#1393 fix(tiny): use path-clean
  Cargo.lock
  util/app-config/Cargo.toml
  util/app-config/src/app_config.rs
Labels: s:waiting-on-author

#1460 chore(ci): allow code coverage failures
  .travis.yml
Labels: s:ready-to-merge

#1465 [ᚬrc/v0.19] feat: Use secp256k1 referenced by hash type "type" as the default lock.
  ckb-bin/src/subcommand/cli/secp256k1_lock.rs
  ckb-bin/src/subcommand/init.rs
  ckb-bin/src/subcommand/run.rs
  docs/hashes.toml
  resource/ckb.toml
  resource/specs/dev.toml
  resource/specs/staging.toml
  resource/specs/testnet.toml
  spec/src/consensus.rs
  test/Cargo.toml
  test/src/node.rs
  util/app-config/src/cli.rs
  util/jsonrpc-types/src/blockchain.rs
Labels: hotfix

#1470 fix: uncle's header should be stored and indexed
  store/src/transaction.rs
  verification/src/tests/uncle_verifier.rs
Labels: backport rc/v0.19, s:ready-to-merge

#1468 chore: upgrade molecule to solving lifetime issues
  Cargo.lock
  Makefile
  spec/src/consensus.rs
  sync/src/relayer/mod.rs
  util/types/Cargo.toml
  util/types/src/generated/types.rs
Labels: backport rc/v0.19, s:ready-to-merge

#1473 chore: fix coverage test
  Makefile
Labels: s:ready-to-merge

#1478 fix: uncle header shouldn't be deleted when block detach from mainchain
  chain/src/tests/find_fork.rs
  chain/src/tests/util.rs
  store/src/transaction.rs
Labels: backport rc/v0.19, s:ready-to-merge, urgent

#1475 fix: should update cached missing_indexes when collision
  sync/src/relayer/block_transactions_process.rs
  sync/src/relayer/tests/block_transactions_process.rs
Labels: backport rc/v0.19, s:ready-to-merge, urgent

#1490 fix: block header should keep consistency with ext in storage
  store/src/store.rs
  store/src/transaction.rs
  test/src/main.rs
  test/src/specs/sync/block_sync.rs
  util/types/src/core/advanced_builders.rs
  verification/src/contextual_block_verifier.rs
Labels: b:database, backport rc/v0.19, s:ready-to-merge, urgent

#1499 test: fix integration test
  test/src/node.rs
  test/src/specs/sync/chain_forks.rs
Labels: backport rc/v0.19, s:ready-to-merge

#1459 test: Enhanced ibd process test
  test/src/main.rs
  test/src/specs/sync/ibd_process.rs
Labels: s:ready-to-merge

#1489 test: test dep groups in test_bundled_specs
  spec/src/lib.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1506 chore: Suppress ckb init warnings in integration test
  test/src/node.rs
Labels: s:ready-to-merge

#1502 Fix invalid usage of vector builder method.
  test/src/specs/sync/chain_forks.rs
Labels: s:ready-to-merge
