Repository nervosnetwork/ckb, pull requests merged in 2019-06, with the labels that each got.

#913 New verification model
  benches/benches/process_block.rs
  chain/src/tests/basic.rs
  chain/src/tests/util.rs
  core/src/cell.rs
  core/src/transaction.rs
  docs/hashes.toml
  protocol/src/builder.rs
  protocol/src/convert.rs
  protocol/src/protocol.fbs
  protocol/src/protocol_generated.rs
  protocol/src/protocol_generated_verifier.rs
  resource/specs/cells/secp256k1_blake160_sighash_all
  resource/specs/dev.toml
  resource/specs/testnet.toml
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/test.rs
  script/src/lib.rs
  script/src/syscalls/load_cell.rs
  script/src/syscalls/load_header.rs
  script/src/syscalls/load_input.rs
  script/src/syscalls/load_witness.rs
  script/src/syscalls/mod.rs
  script/src/verify.rs
  shared/src/tx_pool/orphan.rs
  shared/src/tx_pool/proposed.rs
  shared/tx-pool-executor/src/tx_pool_executor.rs
  sync/src/relayer/tests/compact_block_process.rs
  sync/src/tests/synchronizer.rs
  test/src/node.rs
  test/src/specs/mining/size_limit.rs
  test/src/specs/relay/transaction_relay.rs
  util/dao/utils/src/lib.rs
  util/jsonrpc-types/src/blockchain.rs
  verification/src/tests/block_verifier.rs
  verification/src/tests/commit_verifier.rs
  verification/src/tests/transaction_verifier.rs
Labels: b:consensus, b:database, b:p2p, b:rpc

#956 chore: upgrade mio dependence
  Cargo.lock
Labels: dependencies

#910 feat: network alert
  Cargo.lock
  Cargo.toml
  ckb-bin/Cargo.toml
  ckb-bin/src/subcommand/run.rs
  core/src/alert.rs
  core/src/lib.rs
  protocol/src/builder.rs
  protocol/src/convert.rs
  protocol/src/protocol.fbs
  protocol/src/protocol_generated.rs
  protocol/src/protocol_generated_verifier.rs
  rpc/Cargo.toml
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/config.rs
  rpc/src/lib.rs
  rpc/src/module/alert.rs
  rpc/src/module/mod.rs
  rpc/src/module/stats.rs
  rpc/src/server.rs
  rpc/src/service_builder.rs
  rpc/src/test.rs
  sync/src/lib.rs
  test/Cargo.toml
  test/src/main.rs
  test/src/rpc.rs
  test/src/specs/alert/alert_propagation.rs
  test/src/specs/alert/mod.rs
  test/src/specs/mod.rs
  util/app-config/Cargo.toml
  util/app-config/src/app_config.rs
  util/crypto/src/secp/privkey.rs
  util/crypto/src/secp/signature.rs
  util/jsonrpc-types/src/alert.rs
  util/jsonrpc-types/src/chain_info.rs
  util/jsonrpc-types/src/lib.rs
  util/network-alert/Cargo.toml
  util/network-alert/src/alert.toml
  util/network-alert/src/alert_relayer.rs
  util/network-alert/src/config.rs
  util/network-alert/src/lib.rs
  util/network-alert/src/notifier.rs
  util/network-alert/src/verifier.rs
Labels: b:p2p, breaking change, s:waiting-on-author

#963 fix: RPC enable modules typo
  rpc/src/service_builder.rs
Labels: t:bug

#962 chore: sign git release assets
  .travis.yml
  azure-pipelines.yml
  devtools/ci/package.sh
  devtools/ci/travis-secret.asc.enc
  docs/get-ckb.md
  docs/integrity-check.md
Labels: hotfix

#966 [ᚬrc/v0.14.0] Backport windows support and sentry cleanup to v0.14.0
  .travis.yml
  Cargo.lock
  Makefile
  azure-pipelines.yml
  ckb-bin/Cargo.toml
  ckb-bin/src/subcommand/init.rs
  devtools/azure/windows-dependencies.yml
  devtools/ci/package.sh
  devtools/ci/travis-secret.asc.enc
  docs/get-ckb.md
  docs/integrity-check.md
  miner/src/client.rs
  network/src/network.rs
  resource/ckb.toml
  resource/src/lib.rs
  resource/src/template.rs
  rpc/src/module/miner.rs
  script/Cargo.toml
  script/src/lib.rs
  script/src/verify.rs
  sync/src/relayer/transaction_process.rs
  test/src/net.rs
  test/src/node.rs
  test/src/specs/relay/compact_block.rs
  test/src/specs/relay/transaction_relay.rs
  test/src/specs/sync/chain_forks.rs
  test/src/specs/sync/sync_timeout.rs
  test/src/specs/tx_pool/pool_reconcile.rs
  test/src/specs/tx_pool/pool_resurrect.rs
  util/app-config/src/app_config.rs
  util/hash/Cargo.toml
Labels: hotfix

#961 [ᚬrc/v0.14.0] [BREAKCHANGE] feat: display miner worker status
  Cargo.lock
  benches/benches/cuckoo.rs
  ckb-bin/src/subcommand/miner.rs
  core/src/header.rs
  devtools/init/linux-systemd/ckb-miner.service
  docs/ckb-core-dev.md
  miner/Cargo.toml
  miner/src/block_assembler.rs
  miner/src/client.rs
  miner/src/config.rs
  miner/src/lib.rs
  miner/src/miner.rs
  miner/src/worker/cuckoo_simple.rs
  miner/src/worker/dummy.rs
  miner/src/worker/mod.rs
  pow/Cargo.toml
  pow/src/cuckoo.rs
  pow/src/dummy.rs
  pow/src/lib.rs
  resource/ckb-miner.toml
  spec/src/consensus.rs
  test/integration.toml
  util/app-config/src/app_config.rs
Labels: hotfix

#939 feat: explicitly specify bundled or file system
  Cargo.lock
  ckb-bin/src/lib.rs
  ckb-bin/src/subcommand/cli/hashes.rs
  ckb-bin/src/subcommand/init.rs
  db/src/config.rs
  docs/configure.md
  resource/Cargo.toml
  resource/ckb-miner.toml
  resource/ckb.toml
  resource/specs/dev.toml
  resource/specs/testnet.toml
  resource/src/lib.rs
  script/src/verify.rs
  spec/src/lib.rs
  test/integration.toml
  test/src/node.rs
  util/app-config/src/app_config.rs
  util/app-config/src/args.rs
  util/app-config/src/lib.rs
Labels: b:cli, breaking change

#981 [ᚬrc/v0.14.0] perf(sync): Fix get ancestor performance issue
  Cargo.lock
  sync/Cargo.toml
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/synchronizer.rs
  sync/src/types.rs
Labels: hotfix

#978 feat: use new identify protocol
  Cargo.lock
  ckb-bin/src/subcommand/run.rs
  network/Cargo.toml
  network/src/network.rs
  network/src/protocols/identify.rs
  network/src/services/outbound_peer.rs
  protocol/src/lib.rs
  protocol/src/protocol.fbs
  protocol/src/protocol_generated.rs
  protocol/src/protocol_generated_verifier.rs
  rpc/src/test.rs
  spec/src/consensus.rs
  test/src/net.rs
  test/src/node.rs
  test/src/specs/mod.rs
Labels: b:p2p, breaking change

#922 feat: proposer reward
  Cargo.lock
  Cargo.toml
  chain/src/chain.rs
  chain/src/tests/find_fork.rs
  chain/src/tests/mod.rs
  chain/src/tests/reward.rs
  chain/src/tests/util.rs
  core/src/extras.rs
  core/src/header.rs
  core/src/script.rs
  core/src/transaction.rs
  docs/hashes.toml
  miner/src/block_assembler.rs
  resource/specs/dev.toml
  resource/specs/testnet.toml
  rpc/src/test.rs
  script/src/verify.rs
  shared/Cargo.toml
  shared/src/chain_state.rs
  shared/src/shared.rs
  shared/src/tx_proposal_table.rs
  shared/tx-pool-executor/src/tx_pool_executor.rs
  spec/src/consensus.rs
  spec/src/lib.rs
  store/src/store.rs
  sync/src/relayer/tests/compact_block_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/synchronizer.rs
  test/integration.toml
  test/src/main.rs
  test/src/specs/mining/bootstrap.rs
  test/src/specs/mining/mod.rs
  test/src/specs/mining/size_limit.rs
  traits/Cargo.toml
  traits/src/chain_provider.rs
  util/occupied-capacity/core/src/lib.rs
  util/occupied-capacity/core/src/units.rs
  util/occupied-capacity/src/lib.rs
  util/reward-calculator/Cargo.toml
  util/reward-calculator/src/lib.rs
  util/test-chain-utils/Cargo.toml
  util/test-chain-utils/src/lib.rs
  verification/Cargo.toml
  verification/src/block_verifier.rs
  verification/src/contextual_block_verifier.rs
  verification/src/error.rs
  verification/src/tests/block_verifier.rs
  verification/src/tests/commit_verifier.rs
  verification/src/tests/dummy.rs
Labels: b:consensus, breaking change, m:consensus

#983 [ᚬrc/v0.14.0] fix: uncle number should smaller than block
  miner/src/block_assembler.rs
  verification/src/error.rs
  verification/src/tests/uncle_verifier.rs
  verification/src/uncles_verifier.rs
Labels: b:consensus, hotfix, m:consensus

#1003 [ᚬrc/v0.14.0] chore: package linux binary using Ubuntu 16
  .travis.yml
Labels: hotfix

#1001 [ᚬrc/v0.14.0] feat: `ckb init` supports setting block assembler
  ckb-bin/src/subcommand/cli/secp256k1_lock.rs
  ckb-bin/src/subcommand/init.rs
  resource/ckb.toml
  resource/src/template.rs
  util/app-config/src/app_config.rs
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/lib.rs
Labels: hotfix

#996 [ᚬrc/v0.14.0] feat: Tweak consensus parameters
  chain/src/tests/basic.rs
  chain/src/tests/util.rs
  resource/specs/dev.toml
  resource/specs/testnet.toml
  rpc/README.md
  rpc/json/rpc.json
  spec/src/consensus.rs
  test/integration.toml
  test/src/node.rs
  test/src/specs/relay/transaction_relay.rs
Labels: hotfix

#1018 [ᚬrc/v0.14.0] chore: print found seal information
  miner/src/miner.rs
  miner/src/worker/cuckoo_simple.rs
  miner/src/worker/mod.rs
Labels: hotfix

#1019 [ᚬrc/v0.14.0] fix: miner log wrong block hash
  miner/src/miner.rs
Labels: hotfix

#1022 fix: avoid dummy worker re-solve the same works
  miner/src/worker/dummy.rs
Labels: hotfix

#1025 [ᚬrc/v0.14.0] fix: miner time interval panic
  miner/src/worker/cuckoo_simple.rs
Labels: hotfix

#1027 [ᚬrc/v0.14.0] chore: sentry events filter
  util/app-config/src/sentry_config.rs
Labels: hotfix

#1034 [ᚬrc/v0.14.0] chore: use fixed interval for miner state output
  miner/src/worker/cuckoo_simple.rs
Labels: hotfix

#1054 Replace system cell
  Cargo.lock
  docs/hashes.toml
  resource/Cargo.toml
  resource/build.rs
  resource/specs/cells/secp256k1_blake160_sighash_all
  resource/specs/dev.toml
  resource/specs/testnet.toml
  resource/src/lib.rs
  script/src/verify.rs
Labels: b:consensus, breaking change

#1055 feat: add an extra cost for dynamic length types
  core/src/block.rs
  core/src/script.rs
  core/src/transaction.rs
  docs/hashes.toml
  resource/specs/dev.toml
  resource/specs/testnet.toml
  rpc/README.md
  rpc/json/rpc.json
  test/src/specs/mining/size_limit.rs
  test/src/specs/tx_pool/limit.rs
  util/occupied-capacity/core/src/traits.rs
  util/occupied-capacity/core/src/units.rs
  util/occupied-capacity/tests/tests.rs
Labels: b:consensus, breaking change

#1062 refactor: remove extra cost from capacity and simplify the occupied capacity
  benches/benches/process_block.rs
  core/src/lib.rs
  core/src/script.rs
  core/src/transaction.rs
  docs/hashes.toml
  miner/src/block_assembler.rs
  resource/specs/dev.toml
  resource/specs/testnet.toml
  spec/src/lib.rs
  util/dao/src/lib.rs
  util/occupied-capacity/core/src/lib.rs
  util/occupied-capacity/core/src/traits.rs
  util/occupied-capacity/core/src/units.rs
  util/occupied-capacity/macros/src/lib.rs
  util/occupied-capacity/src/lib.rs
  util/occupied-capacity/tests/tests.rs
  verification/src/transaction_verifier.rs
Labels: breaking change

#1076 [ᚬrc/v0.14.0] fix: cellset consistency
  chain/src/chain.rs
  chain/src/tests/basic.rs
  chain/src/tests/delay_verify.rs
  chain/src/tests/util.rs
  core/src/block.rs
  core/src/transaction.rs
  miner/src/block_assembler.rs
  miner/src/client.rs
  shared/src/cell_set.rs
  shared/src/chain_state.rs
  shared/src/tx_pool/orphan.rs
  shared/src/tx_pool/proposed.rs
  shared/tx-pool-executor/src/tx_pool_executor.rs
  test/src/node.rs
  test/src/utils.rs
Labels: hotfix, urgent

#1088 feat: revise epoch rpc
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/module/chain.rs
  test/src/rpc.rs
  util/jsonrpc-types/src/blockchain.rs
  util/jsonrpc-types/src/lib.rs
Labels: b:rpc, breaking change

#1032 refactor(storage): use flatbuffer instead of bincode in storage
  Cargo.lock
  Cargo.toml
  core/src/extras.rs
  core/src/header.rs
  core/src/transaction_meta.rs
  db/Cargo.toml
  db/src/lib.rs
  db/src/memorydb.rs
  db/src/rocksdb.rs
  protos/Cargo.toml
  protos/gen_proto.sh
  protos/schemas/common.fbs
  protos/schemas/storage.fbs
  protos/src/convert/from_common.rs
  protos/src/convert/from_storage.rs
  protos/src/convert/mod.rs
  protos/src/convert/to_common.rs
  protos/src/convert/to_storage.rs
  protos/src/error.rs
  protos/src/generated/common.rs
  protos/src/generated/extra_methods.rs
  protos/src/generated/mod.rs
  protos/src/generated/storage.rs
  protos/src/lib.rs
  shared/src/chain_state.rs
  store/Cargo.toml
  store/src/flat_block_body.rs
  store/src/lib.rs
  store/src/store.rs
Labels: b:database, breaking change

#1119 feat: Remove rules of special reserve blocks
  benches/benches/process_block.rs
  chain/src/tests/basic.rs
  chain/src/tests/reward.rs
  chain/src/tests/util.rs
  docs/hashes.toml
  miner/src/block_assembler.rs
  resource/specs/testnet.toml
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/test.rs
  shared/tx-pool-executor/src/tx_pool_executor.rs
  spec/src/consensus.rs
  spec/src/lib.rs
  sync/src/relayer/tests/compact_block_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/synchronizer.rs
  util/reward-calculator/src/lib.rs
  verification/src/contextual_block_verifier.rs
  verification/src/tests/commit_verifier.rs
  verification/src/tests/uncle_verifier.rs
Labels: b:consensus, b:database, breaking change
