Repository nervosnetwork/ckb, pull requests merged in 2020-01, with the labels that each got.

#1904 chore: print disconnect reason as info level log
  network/src/protocols/disconnect_message.rs
Labels: s:ready-to-merge

#1906 test: add --locked option on cargo install command
  .travis.yml
  docs/ckb-core-dev.md
Labels: s:ready-to-merge

#1902 chore: Rename withdraw_header to withdrawing_header in DaoCalculator
  util/dao/src/lib.rs
Labels: s:ready-to-merge

#1893 chore(deps): bump jsonrpc-core from 10.1.0 to 14.0.5
  Cargo.lock
  util/jsonrpc-types/Cargo.toml
Labels: s:ready-to-merge

#1896 chore: move protocols to ckb
  Cargo.lock
  Cargo.toml
  Makefile
  devtools/ci/check-cargotoml.sh
  network/Cargo.toml
  protocols/discovery/Cargo.toml
  protocols/discovery/src/addr.rs
  protocols/discovery/src/lib.rs
  protocols/discovery/src/protocol.rs
  protocols/discovery/src/substream.rs
  protocols/identify/Cargo.toml
  protocols/identify/src/lib.rs
  protocols/identify/src/protocol.rs
  protocols/ping/Cargo.toml
  protocols/ping/src/lib.rs
  util/types/schemas/protocols.mol
  util/types/src/generated/mod.rs
  util/types/src/generated/protocols.rs
Labels: s:ready-to-merge

#1908 feat: periodically disconnect peers which open invalid sub-protocols
  ckb-bin/src/subcommand/run.rs
  network/src/network.rs
  network/src/services/mod.rs
  network/src/services/protocol_type_checker.rs
  rpc/src/test.rs
  test/src/net.rs
Labels: s:ready-to-merge

#1880 chore(deps): bump rust-rocksdb from 6.2.4 to 6.4.6
  Cargo.lock
  db/Cargo.toml
Labels: dependencies, s:ready-to-merge

#1916 fix: transaction should be relayed when node connects peers
  sync/src/relayer/mod.rs
  test/src/main.rs
  test/src/specs/relay/transaction_relay.rs
Labels: s:ready-to-merge

#1921 fix: estimate_fee RPC error msg
  rpc/src/module/experiment.rs
Labels: backport rc/v0.27, s:ready-to-merge
