Repository nervosnetwork/ckb, pull requests merged in 2020-12, with the labels that each got.

#2297 chain freezer
  Cargo.lock
  Cargo.toml
  benches/benches/benchmarks/overall.rs
  benches/benches/benchmarks/util.rs
  chain/src/chain.rs
  chain/src/tests/block_assembler.rs
  chain/src/tests/find_fork.rs
  chain/src/tests/truncate.rs
  chain/src/tests/uncle.rs
  chain/src/tests/util.rs
  ckb-bin/src/subcommand/export.rs
  ckb-bin/src/subcommand/import.rs
  ckb-bin/src/subcommand/migrate.rs
  ckb-bin/src/subcommand/replay.rs
  ckb-bin/src/subcommand/run.rs
  ckb-bin/src/subcommand/stats.rs
  db-schema/src/lib.rs
  db/src/db.rs
  db/src/lib.rs
  freezer/Cargo.toml
  freezer/README.md
  freezer/src/freezer.rs
  freezer/src/freezer_files.rs
  freezer/src/lib.rs
  freezer/src/tests.rs
  freezer/tests/failpoints.rs
  indexer/src/store.rs
  rpc/src/test.rs
  shared/Cargo.toml
  shared/src/migrations/add_number_hash_mapping.rs
  shared/src/migrations/mod.rs
  shared/src/shared.rs
  store/Cargo.toml
  store/src/db.rs
  store/src/snapshot.rs
  store/src/store.rs
  store/src/transaction.rs
  store/src/write_batch.rs
  sync/src/relayer/tests/helper.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/sync_shared.rs
  sync/src/tests/synchronizer.rs
  sync/src/tests/util.rs
  util/Cargo.toml
  util/app-config/src/app_config.rs
  util/chain-iter/src/lib.rs
  util/snapshot/Cargo.toml
  util/snapshot/src/lib.rs
  util/test-chain-utils/src/mock_store.rs
  util/types/schemas/extensions.mol
  util/types/src/generated/extensions.rs
  verification/src/tests/contextual_block_verifier.rs
  verification/src/tests/two_phase_commit_verifier.rs
  verification/src/tests/uncle_verifier.rs
Labels: s:blocking

#2448 fix: genesis hash rate estimate
  spec/src/consensus.rs
  spec/src/lib.rs
Labels: urgent

#2452 Upgrade dependencies tiny-keccak base64 and rand
  Cargo.lock
  benches/Cargo.toml
  ckb-bin/Cargo.toml
  miner/Cargo.toml
  miner/src/worker/dummy.rs
  miner/src/worker/mod.rs
  network/Cargo.toml
  script/Cargo.toml
  script/src/verify.rs
  sync/Cargo.toml
  test/Cargo.toml
  util/app-config/Cargo.toml
  util/crypto/Cargo.toml
  util/multisig/Cargo.toml
  verification/Cargo.toml
Labels: dependencies

#2453 chore(deps): use patched metrics
  Cargo.lock
  Cargo.toml
  deny.toml
  util/metrics-service/Cargo.toml
  util/metrics/Cargo.toml
Labels: dependencies

#2470 docs: fix reject tx subscription RPC doc
  devtools/doc/rpc.py
  rpc/README.md
  rpc/src/module/subscription.rs
Labels: t:doc
