Repository nervosnetwork/ckb, pull requests merged in 2020-02, with the labels that each got.

#1915 feat: Reject new scripts with known bugs
  Cargo.lock
  ckb-bin/src/subcommand/run.rs
  resource/ckb.toml
  rpc/Cargo.toml
  rpc/src/config.rs
  rpc/src/module/pool.rs
  rpc/src/service_builder.rs
  rpc/src/test.rs
  sync/Cargo.toml
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/helper.rs
  sync/src/relayer/transactions_process.rs
  test/src/specs/tx_pool/send_defected_binary.rs
  tx-pool/Cargo.toml
  tx-pool/src/config.rs
  tx-pool/src/process/submit_txs.rs
  tx-pool/src/service.rs
Labels: s:ready-to-merge

#1922 fix: CKBProtocolContext#connected_peers should filter peers by protoc…
  network/src/protocols/mod.rs
Labels: backport rc/v0.27, s:ready-to-merge

#1924 chore: bump rust toolchain from 1.38.0 to 1.41.0
  .travis.yml
  azure-pipelines.yml
  docker/hub/Dockerfile
  resource/build.rs
  rpc/src/test.rs
  rust-toolchain
Labels: s:ready-to-merge

#1856 feat: Define StatusCode to indicate the result of sync operation
  sync/src/lib.rs
  sync/src/relayer/block_proposal_process.rs
  sync/src/relayer/block_transactions_process.rs
  sync/src/relayer/block_transactions_verifier.rs
  sync/src/relayer/block_uncles_verifier.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/compact_block_verifier.rs
  sync/src/relayer/error.rs
  sync/src/relayer/get_block_proposal_process.rs
  sync/src/relayer/get_block_transactions_process.rs
  sync/src/relayer/get_transactions_process.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/block_proposal_process.rs
  sync/src/relayer/tests/block_transactions_process.rs
  sync/src/relayer/tests/block_transactions_verifier.rs
  sync/src/relayer/tests/compact_block_process.rs
  sync/src/relayer/tests/compact_block_verifier.rs
  sync/src/relayer/tests/reconstruct_block.rs
  sync/src/relayer/transaction_hashes_process.rs
  sync/src/relayer/transactions_process.rs
  sync/src/status.rs
  sync/src/synchronizer/block_process.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/synchronizer/get_headers_process.rs
  sync/src/synchronizer/headers_process.rs
  sync/src/synchronizer/in_ibd_process.rs
  sync/src/synchronizer/mod.rs
  test/src/specs/tx_pool/reference_header_maturity.rs
Labels: s:ready-to-merge

#1928 feat: null outputs_validator means passthrough.
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/module/pool.rs
Labels: breaking change

#1929 chore: ignore spin warning
  Makefile
Labels: s:ready-to-merge

#1941 feat: uses feature flags to enable deadlock detection
  Cargo.toml
  Makefile
  ckb-bin/Cargo.toml
  ckb-bin/src/helper.rs
  util/Cargo.toml
Labels: s:ready-to-merge

#1939 feat: add more info on rpc
  rpc/README.md
  rpc/json/rpc.json
  rpc/src/module/pool.rs
  util/jsonrpc-types/src/pool.rs
Labels: breaking change, s:ready-to-merge

#1931 feat: collect metrics by logger
  Cargo.lock
  chain/src/chain.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/mod.rs
  sync/src/status.rs
  sync/src/synchronizer/mod.rs
  util/logger/Cargo.toml
  util/logger/src/lib.rs
Labels: s:ready-to-merge

#1950 fix: fix incorrect error messages for JSON uints
  util/jsonrpc-types/src/alert.rs
  util/jsonrpc-types/src/lib.rs
  util/jsonrpc-types/src/uint128.rs
  util/jsonrpc-types/src/uint32.rs
  util/jsonrpc-types/src/uint64.rs
  util/jsonrpc-types/src/uints.rs
Labels: backport rc/v0.29, s:ready-to-merge
