Repository nervosnetwork/ckb, pull requests merged in 2020-03, with the labels that each got.

#1954 feat: Add detect-asm feature to script
  script/Cargo.toml
Labels: s:ready-to-merge

#1955 feat: Bump CKB VM to fix a performance regression
  Cargo.lock
  devtools/ci/check-cargotoml.sh
  error/Cargo.toml
  script/Cargo.toml
Labels: backport rc/v0.30, s:ready-to-merge

#1948 feat: use module disable error instead of method not found
  Cargo.lock
  error/Cargo.toml
  rpc/src/service_builder.rs
Labels: s:ready-to-merge

#1956 feat: replace rocksdb wrapper
  Cargo.lock
  db/Cargo.toml
Labels: s:ready-to-merge

#1960 test: add options for integration tests and fix a bug
  test/src/main.rs
Labels: s:ready-to-merge

#1946 feat: use same allocator for all
  Cargo.toml
Labels: s:ready-to-merge

#1965 chore: send failed integration test to sentry
  .gitignore
  Makefile
  test/run.sh
  test/src/main.rs
Labels: s:ready-to-merge

#1947 refactory: repair using of snapshot
  chain/src/chain.rs
  chain/src/tests/mod.rs
  chain/src/tests/uncle.rs
  ckb-bin/src/subcommand/run.rs
  db/src/db.rs
  db/src/snapshot.rs
  rpc/src/module/pool.rs
  rpc/src/module/stats.rs
  rpc/src/service_builder.rs
  rpc/src/test.rs
  shared/src/shared.rs
  sync/src/lib.rs
  sync/src/relayer/block_proposal_process.rs
  sync/src/relayer/block_transactions_process.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/get_block_proposal_process.rs
  sync/src/relayer/get_block_transactions_process.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/block_transactions_process.rs
  sync/src/relayer/tests/compact_block_process.rs
  sync/src/relayer/tests/helper.rs
  sync/src/relayer/tests/reconstruct_block.rs
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/block_process.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/synchronizer/get_headers_process.rs
  sync/src/synchronizer/headers_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/mod.rs
  sync/src/tests/sync_shared.rs
  sync/src/tests/synchronizer.rs
  sync/src/tests/util.rs
  sync/src/types.rs
  util/snapshot/src/lib.rs
Labels: hotfix, pinned, staged, t:bug

#1961 fix: fix bug on last common marked
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/tests/compact_block_process.rs
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/mod.rs
Labels: s:ready-to-merge, s:waiting-on-author

#1957 feat: concurrent download blocks on ibd
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/get_headers_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/types.rs
Labels: s:waiting-on-author

#1966 feat: enhanced locator
  sync/src/types.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1974 test: fix test
  test/src/node.rs
Labels: backport rc/v0.30, s:ready-to-merge

#1881 feat: remove memory cellset
  Cargo.lock
  chain/Cargo.toml
  chain/src/cell.rs
  chain/src/chain.rs
  rpc/src/module/chain.rs
  shared/Cargo.toml
  shared/src/lib.rs
  shared/src/shared.rs
  store/src/db.rs
  store/src/store.rs
  util/snapshot/Cargo.toml
  util/snapshot/src/lib.rs
Labels: pinned, s:ready-to-merge, s:waiting-on-author

#1959 perf: improve get_ancestor efficiency
  sync/src/synchronizer/block_fetcher.rs
  sync/src/types.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1975 chore: reset testnet aggron genesis
  docs/hashes.toml
  resource/specs/testnet.toml
Labels: backport rc/v0.30

#1923 feat: network upgrade to async
  Cargo.lock
  network/Cargo.toml
  network/src/compress.rs
  network/src/config.rs
  network/src/network.rs
  network/src/peer_store/types.rs
  network/src/protocols/discovery.rs
  network/src/protocols/identify.rs
  network/src/protocols/mod.rs
  network/src/protocols/ping.rs
  network/src/protocols/test.rs
  network/src/services/dns_seeding/mod.rs
  network/src/services/dns_seeding/seed_record.rs
  network/src/services/dump_peer_store.rs
  network/src/services/outbound_peer.rs
  network/src/services/protocol_type_checker.rs
  network/src/tests/peer_store.rs
  protocols/discovery/Cargo.toml
  protocols/discovery/src/addr.rs
  protocols/discovery/src/lib.rs
  protocols/discovery/src/protocol.rs
  protocols/discovery/src/substream.rs
  protocols/identify/Cargo.toml
  protocols/identify/src/lib.rs
  protocols/identify/src/protocol.rs
  protocols/ping/Cargo.toml
  protocols/ping/src/lib.rs
  rpc/src/module/alert.rs
  rpc/src/module/miner.rs
  rpc/src/module/test.rs
  spec/src/lib.rs
  sync/Cargo.toml
  sync/src/net_time_checker.rs
  sync/src/relayer/block_transactions_process.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/get_block_proposal_process.rs
  sync/src/relayer/get_block_transactions_process.rs
  sync/src/relayer/get_transactions_process.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/block_transactions_process.rs
  sync/src/relayer/tests/compact_block_process.rs
  sync/src/relayer/tests/helper.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/synchronizer/get_headers_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/mod.rs
  sync/src/types.rs
  test/src/specs/relay/get_block_transactions_process.rs
  test/src/specs/sync/invalid_locator_size.rs
  test/src/utils.rs
  util/crypto/Cargo.toml
  util/network-alert/src/alert_relayer.rs
Labels: s:waiting-on-author

#1977 fix: Fix false positive in IllTransactionChecker
  script/src/ill_transaction_checker.rs
  script/testdata/jalr_zero
  script/testdata/jalr_zero.S
Labels: backport rc/v0.30, backport rc/v0.31, s:ready-to-merge

#1978 feat: built-in miner should support https rpc url
  Cargo.lock
  miner/Cargo.toml
  miner/src/client.rs
Labels: s:ready-to-merge

#1984 chore: Update SECURITY.md to fix the mailto link
  SECURITY.md
Labels: backport rc/v0.31

#1985 perf: Speed up fetch collect
  sync/src/synchronizer/block_fetcher.rs
Labels: s:ready-to-merge

#1958 feat: Log more sync and relay metrics
  chain/src/chain.rs
  sync/src/relayer/block_transactions_process.rs
  sync/src/relayer/compact_block_process.rs
  sync/src/relayer/get_block_proposal_process.rs
  sync/src/relayer/get_block_transactions_process.rs
  sync/src/relayer/get_transactions_process.rs
  sync/src/relayer/mod.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/synchronizer/get_headers_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/types.rs
  util/logger/src/lib.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#1989 [ᚬrc/v0.30] perf: Fix build_skip performance bug
  Cargo.lock
  error/Cargo.toml
  sync/src/types.rs
Labels: hotfix, s:ready-to-merge
