Repository nervosnetwork/ckb, pull requests merged in 2020-04, with the labels that each got.

#1992 feat: add an option to control how many blocks the miner has to mine
  ckb-bin/src/lib.rs
  ckb-bin/src/subcommand/miner.rs
  miner/src/miner.rs
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/lib.rs
Labels: s:ready-to-merge

#1993 feat: Add metrics filter
  util/logger/src/lib.rs
Labels: s:ready-to-merge

#1996 fix: wait for RPC server to cleanup on shutdown
  rpc/src/server.rs
  rpc/src/test.rs
Labels: s:ready-to-merge

#1991 chore: upgrade tentacle
  Cargo.lock
  network/Cargo.toml
  network/src/network.rs
Labels: s:ready-to-merge

#1997 fix: orphan_block_pool should record block origin
  sync/src/orphan_block_pool.rs
  sync/src/types.rs
Labels: backport rc/v0.31, s:ready-to-merge

#1990 chore: export OutputsValidator
  rpc/src/module/pool.rs
  util/jsonrpc-types/src/lib.rs
  util/jsonrpc-types/src/pool.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#2002 feat: avoid explosion of disordering blocks based on BLOCK_DOWNLOAD_WINDOW
  sync/src/lib.rs
  sync/src/synchronizer/block_fetcher.rs
Labels: s:ready-to-merge

#1973 chore: Cleanup Environments
  .github/ISSUE_TEMPLATE/bug_report.md
  docs/hashes.toml
  resource/ckb-miner.toml
  resource/ckb.toml
  resource/specs/staging.toml
  resource/src/template.rs
Labels: s:ready-to-merge

#2003 docs: add few comments into schema files
  util/types/schemas/blockchain.mol
  util/types/schemas/extensions.mol
Labels: s:ready-to-merge

#2005 chore: upgrade tokio
  Cargo.lock
Labels: backport rc/v0.31, s:ready-to-merge

#2013 [ᚬrc/v0.31] chore: upgrade tokio
  Cargo.lock
Labels: hotfix, s:ready-to-merge

#1968 refactor: Simplify network protocols
  Cargo.lock
  Cargo.toml
  network/Cargo.toml
  network/src/network.rs
  network/src/protocols/discovery.rs
  network/src/protocols/discovery/addr.rs
  network/src/protocols/discovery/mod.rs
  network/src/protocols/discovery/protocol.rs
  network/src/protocols/discovery/substream.rs
  network/src/protocols/identify.rs
  network/src/protocols/identify/mod.rs
  network/src/protocols/identify/protocol.rs
  network/src/protocols/ping.rs
  network/src/protocols/test.rs
  protocols/discovery/Cargo.toml
  protocols/identify/Cargo.toml
  protocols/ping/Cargo.toml
  protocols/ping/src/lib.rs
Labels: s:ready-to-merge, s:waiting-on-reviewers

#2016 chore: typo
  sync/src/types.rs
Labels: s:ready-to-merge

#2017 chore: bump jsonrpc from 14.0.5 to 14.1.0
  Cargo.lock
  ckb-bin/src/subcommand/run.rs
  rpc/Cargo.toml
  rpc/src/server.rs
  rpc/src/test.rs
Labels: dependencies

#2015 chore: use self-hosted sentry for testnet
  resource/ckb-miner.toml
  resource/ckb.toml
Labels: s:ready-to-merge

#2018 feat: prof command support specify execution path
  Cargo.lock
  ckb-bin/Cargo.toml
  ckb-bin/src/subcommand/prof.rs
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/lib.rs
Labels: s:ready-to-merge

#2021 chore: Update README.md for typo
  README.md
Labels: s:ready-to-merge
