Repository nervosnetwork/ckb, pull requests merged in 2021-07, with the labels that each got.

#2796 feat(hardfork): net hardfork
  docs/hashes.toml
  network/src/network.rs
  network/src/protocols/discovery/mod.rs
  network/src/protocols/discovery/protocol.rs
  network/src/protocols/discovery/state.rs
  network/src/protocols/identify/mod.rs
  network/src/protocols/mod.rs
  network/src/protocols/support_protocols.rs
  resource/specs/dev.toml
  rpc/src/module/miner.rs
  script/src/verify.rs
  shared/src/shared.rs
  spec/src/hardfork.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/tests/helper.rs
  sync/src/synchronizer/get_blocks_process.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/mod.rs
  sync/src/types/mod.rs
  test/src/specs/hardfork/v2021/vm_version.rs
  tx-pool/src/process.rs
  tx-pool/src/service.rs
  util/constant/src/sync.rs
  util/launcher/src/lib.rs
  util/launcher/src/shared_builder.rs
  util/types/schemas/protocols.mol
  util/types/src/core/hardfork.rs
  util/types/src/generated/protocols.rs
Labels: ckb2021, s:waiting-on-reviewers

#2776 refactor(hardfork): rename JSON RPC field "uncles_hash" to "extra_hash"
  rpc/README.md
  rpc/src/module/chain.rs
  rpc/src/module/miner.rs
  util/jsonrpc-types/src/blockchain.rs
Labels: b:rpc, breaking change, ckb2021, s:waiting-on-reviewers

#2799 resumeble verification
  Cargo.lock
  chain/src/chain.rs
  ckb-bin/src/subcommand/import.rs
  miner/src/client.rs
  network/src/network.rs
  notify/src/lib.rs
  resource/ckb.toml
  rpc/src/module/test.rs
  script/Cargo.toml
  script/src/cost_model.rs
  script/src/error.rs
  script/src/lib.rs
  script/src/syscalls/debugger.rs
  script/src/syscalls/exec.rs
  script/src/syscalls/load_cell.rs
  script/src/syscalls/load_cell_data.rs
  script/src/syscalls/load_header.rs
  script/src/syscalls/load_input.rs
  script/src/syscalls/load_script.rs
  script/src/syscalls/load_script_hash.rs
  script/src/syscalls/load_tx.rs
  script/src/syscalls/load_witness.rs
  script/src/types.rs
  script/src/verify.rs
  shared/src/shared.rs
  sync/src/relayer/mod.rs
  sync/src/relayer/transactions_process.rs
  test/src/main.rs
  test/src/node.rs
  test/src/rpc.rs
  test/src/specs/tx_pool/send_large_cycles_tx.rs
  test/template/ckb.toml
  tx-pool/Cargo.toml
  tx-pool/src/chunk_process.rs
  tx-pool/src/component/chunk.rs
  tx-pool/src/component/mod.rs
  tx-pool/src/component/orphan.rs
  tx-pool/src/error.rs
  tx-pool/src/lib.rs
  tx-pool/src/pool.rs
  tx-pool/src/process.rs
  tx-pool/src/service.rs
  tx-pool/src/util.rs
  util/app-config/src/configs/tx_pool.rs
  util/channel/src/lib.rs
  util/launcher/Cargo.toml
  util/launcher/src/shared_builder.rs
  util/logger-service/Cargo.toml
  util/runtime/src/lib.rs
  util/stop-handler/src/lib.rs
  util/types/Cargo.toml
  verification/contextual/src/contextual_block_verifier.rs
  verification/src/cache.rs
  verification/src/lib.rs
  verification/src/transaction_verifier.rs
Labels: ckb2021, p:must-have, s:blocking, s:waiting-on-reviewers

#2818 refactor(hardfork): change field "hash_type" to an enumerated type
  Cargo.lock
  benches/benches/benchmarks/util.rs
  chain/src/tests/block_assembler.rs
  chain/src/tests/reward.rs
  chain/src/tests/util.rs
  ckb-bin/src/subcommand/init.rs
  docs/hashes.toml
  resource/specs/dev.toml
  rpc/README.md
  rpc/src/module/chain.rs
  rpc/src/module/experiment.rs
  rpc/src/module/miner.rs
  rpc/src/module/pool.rs
  script/src/error.rs
  script/src/syscalls/mod.rs
  script/src/verify.rs
  spec/src/legacy/v2019.rs
  spec/src/lib.rs
  test/Cargo.toml
  test/src/main.rs
  test/src/node.rs
  test/src/specs/hardfork/v2021/cell_deps.rs
  test/src/specs/hardfork/v2021/vm_version.rs
  test/src/specs/mining/bootstrap.rs
  test/src/specs/tx_pool/mod.rs
  test/src/specs/tx_pool/send_multisig_secp_tx.rs
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/legacy/v2019.rs
  util/app-config/src/lib.rs
  util/constant/Cargo.toml
  util/constant/src/lib.rs
  util/jsonrpc-types/Cargo.toml
  util/jsonrpc-types/src/blockchain.rs
  util/jsonrpc-types/src/cell.rs
  util/jsonrpc-types/src/lib.rs
  util/jsonrpc-types/src/primitive.rs
  util/test-chain-utils/src/chain.rs
  util/types/Cargo.toml
  util/types/src/core/blockchain.rs
  verification/src/transaction_verifier.rs
Labels: b:cli, b:rpc, ckb2021, s:waiting-on-reviewers

#2802 refactor(tests): simplify several construction functions and double ckb script tests
  script/src/lib.rs
  script/src/syscalls/mod.rs
  script/src/syscalls/tests/mod.rs
  script/src/syscalls/tests/utils.rs
  script/src/syscalls/tests/vm_latest/mod.rs
  script/src/syscalls/tests/vm_latest/syscalls_1.rs
  script/src/syscalls/tests/vm_latest/syscalls_2.rs
  script/src/syscalls/tests/vm_version_0.rs
  script/src/types.rs
  script/src/verify.rs
  script/src/verify/tests/ckb_2019.rs
  script/src/verify/tests/ckb_latest/features_since_v2019.rs
  script/src/verify/tests/ckb_latest/features_since_v2021.rs
  script/src/verify/tests/ckb_latest/mod.rs
  script/src/verify/tests/mod.rs
  script/src/verify/tests/utils.rs
Labels: ckb2021, s:waiting-on-reviewers, t:test

#2821 feat: change default `OutputsValidator` to `well_known_scripts_only`
  Cargo.lock
  rpc/Cargo.toml
  rpc/README.md
  rpc/src/module/mod.rs
  rpc/src/module/pool.rs
  rpc/src/service_builder.rs
  rpc/src/test.rs
  util/app-config/src/configs/rpc.rs
  util/jsonrpc-types/src/pool.rs
  util/launcher/src/lib.rs
Labels: breaking change, ckb2021

#2831 chore: hardfork related trivial changes
  docs/hashes.toml
  resource/specs/dev.toml
  script/src/verify/tests/utils.rs
  spec/src/hardfork.rs
  test/src/main.rs
  test/src/specs/hardfork/v2021/cell_deps.rs
  test/src/specs/hardfork/v2021/extension.rs
  test/src/specs/hardfork/v2021/header_deps.rs
  test/src/specs/hardfork/v2021/since.rs
  test/src/specs/hardfork/v2021/vm_version.rs
  tx-pool/src/process.rs
  util/launcher/src/lib.rs
  util/types/src/core/hardfork.rs
  verification/src/tests/block_verifier.rs
  verification/src/tests/transaction_verifier.rs
Labels: ckb2021, s:waiting-on-reviewers

#2745 feat: schedule benchmark and sync-mainnet
  .github/workflows/benchmark.yml
  .github/workflows/sync.yml
  .github/workflows/sync/ansible/playbook.yml
  .github/workflows/sync/terraform/main.tf
  .github/workflows/sync/terraform/scripts/main.tf.template
  .github/workflows/sync/terraform/variables.tf
Labels: t:ci

#2777 chore(deps): upgrade several dependencies to remove the oldest version of rand
  Cargo.lock
  benches/Cargo.toml
  network/Cargo.toml
  resource/Cargo.toml
  script/Cargo.toml
  util/jsonrpc-types/Cargo.toml
  util/rational/Cargo.toml
  util/types/Cargo.toml
Labels: dependencies

#2864 chore(deps): upgrade several dependencies to remove tokio less than v1.0
  Cargo.lock
  ckb-bin/Cargo.toml
  deny.toml
  miner/Cargo.toml
  miner/src/client.rs
  network/Cargo.toml
  network/src/services/dns_seeding/mod.rs
  rpc/Cargo.toml
  sync/Cargo.toml
  test/Cargo.toml
  tx-pool/Cargo.toml
  tx-pool/src/error.rs
  tx-pool/src/service.rs
  util/app-config/Cargo.toml
  util/channel/src/lib.rs
  util/logger-service/Cargo.toml
Labels: dependencies, s:waiting-on-reviewers

#2867 chore(hardfork): update RFC numbers and links
  docs/hashes.toml
  resource/specs/dev.toml
  rpc/README.md
  script/src/verify/tests/utils.rs
  spec/src/hardfork.rs
  test/src/specs/hardfork/v2021/cell_deps.rs
  test/src/specs/hardfork/v2021/extension.rs
  test/src/specs/hardfork/v2021/header_deps.rs
  test/src/specs/hardfork/v2021/since.rs
  test/src/specs/hardfork/v2021/vm_version.rs
  util/jsonrpc-types/src/blockchain.rs
  util/types/src/core/hardfork.rs
  verification/src/tests/block_verifier.rs
  verification/src/tests/transaction_verifier.rs
Labels: ckb2021

#2849 feat: remove old version peer from peer store on fork
  network/src/network.rs
  network/src/peer_registry.rs
  network/src/peer_store/peer_store_impl.rs
  network/src/protocols/feeler.rs
  network/src/protocols/identify/mod.rs
  network/src/tests/peer_store.rs
Labels: ckb2021

#2877 fix: don't panic when the database is created by a higher version executable binary
  ckb-bin/src/subcommand/migrate.rs
  db-migration/src/lib.rs
  util/launcher/src/migrate.rs
  util/launcher/src/shared_builder.rs
Labels: s:waiting-on-ci
