Repository nervosnetwork/ckb, pull requests merged in 2021-09, with the labels that each got.

#3023 perf: switch global alloc to tikv-jemallocator
  Cargo.lock
  Cargo.toml
  src/main.rs
  util/memory-tracker/Cargo.toml
Labels: s:discussion-needed, s:bench-needed, s:information-needed

#2984 fix: tx-pool snapshot consistency
  Cargo.lock
  benches/benches/benchmarks/overall.rs
  chain/Cargo.toml
  chain/src/tests/block_assembler.rs
  chain/src/tests/dep_cell.rs
  rpc/src/module/miner.rs
  rpc/src/module/test.rs
  shared/Cargo.toml
  shared/src/shared.rs
  tx-pool/Cargo.toml
  tx-pool/src/chunk_process.rs
  tx-pool/src/lib.rs
  tx-pool/src/process.rs
  tx-pool/src/service.rs
  tx-pool/src/util.rs
  util/launcher/src/shared_builder.rs
  util/snapshot/Cargo.toml
Labels: s:waiting-on-reviewers

#2979 feat: remove conflict pending for reorg
  tx-pool/src/component/pending.rs
  tx-pool/src/component/proposed.rs
  tx-pool/src/component/tests/mod.rs
  tx-pool/src/component/tests/pending.rs
  tx-pool/src/component/tests/proposed.rs
  tx-pool/src/component/tests/util.rs
  tx-pool/src/pool.rs
  tx-pool/src/process.rs
  util/types/src/core/cell.rs
Labels: s:waiting-on-reviewers

#3049 test: add integration test for rpc `get_raw_tx_pool`
  test/src/main.rs
  test/src/rpc.rs
  test/src/specs/tx_pool/get_raw_tx_pool.rs
  test/src/specs/tx_pool/mod.rs
Labels: s:waiting-on-author
