Repository nervosnetwork/ckb, pull requests merged in 2023-07, with the labels that each got.

#4060 Fix dependency `hermit-abi` yanked
  Cargo.lock
Labels: dependencies

#4063 feat(script): add current_memory syscall
  script/src/syscalls/current_memory.rs
  script/src/syscalls/mod.rs
  script/src/syscalls/spawn.rs
  script/src/verify.rs
  script/src/verify/tests/ckb_latest/features_since_v2023.rs
  script/testdata/Makefile
  script/testdata/spawn_current_memory
  script/testdata/spawn_current_memory.c
Labels: t:enhancement

#4055 Fix bats test, `ckb_run` should wait ckb process exit
  util/app-config/src/tests/ckb_run_replay.bats
Labels: t:ci

#3999 Wait tokio tasks finish before CKB process exit
  Cargo.lock
  Cargo.toml
  benches/benches/benchmarks/overall.rs
  block-filter/src/filter.rs
  chain/src/chain.rs
  chain/src/tests/util.rs
  ckb-bin/Cargo.toml
  ckb-bin/src/helper.rs
  ckb-bin/src/lib.rs
  ckb-bin/src/subcommand/miner.rs
  ckb-bin/src/subcommand/run.rs
  miner/src/client.rs
  miner/src/miner.rs
  network/src/network.rs
  network/src/protocols/tests/mod.rs
  notify/src/lib.rs
  rpc/src/module/subscription.rs
  rpc/src/tests/examples.rs
  rpc/src/tests/mod.rs
  shared/Cargo.toml
  shared/src/shared.rs
  sync/src/relayer/tests/helper.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/net_time_checker.rs
  sync/src/tests/synchronizer/functions.rs
  sync/src/types/header_map/mod.rs
  test/src/net.rs
  tx-pool/Cargo.toml
  tx-pool/src/chunk_process.rs
  tx-pool/src/process.rs
  tx-pool/src/service.rs
  util/app-config/src/tests/ckb_run_replay.bats
  util/app-config/src/tests/cli_test.sh
  util/app-config/src/tests/graceful_shutdown.bats
  util/channel/src/lib.rs
  util/indexer/src/service.rs
  util/launcher/Cargo.toml
  util/launcher/src/lib.rs
  util/launcher/src/shared_builder.rs
  util/light-client-protocol-server/src/tests/utils/chain.rs
  util/metrics-service/Cargo.toml
  util/metrics-service/src/lib.rs
  util/network-alert/Cargo.toml
  util/network-alert/src/tests/test_notifier.rs
  util/runtime/Cargo.toml
  util/runtime/src/lib.rs
  util/stop-handler/Cargo.toml
  util/stop-handler/src/lib.rs
  util/stop-handler/src/stop_register.rs
  util/stop-handler/src/tests.rs
Labels: t:enhancement, s:pr-created
