Repository nervosnetwork/ckb, pull requests merged in 2023-10, with the labels that each got.

#4186 Remove `Consensus.dao_type_hash`'s `Option` wrapper
  rpc/README.md
  rpc/src/module/chain.rs
  rpc/src/module/pool.rs
  rpc/src/tests/module/pool.rs
  spec/src/consensus.rs
  test/src/specs/dao/dao_user.rs
  test/src/specs/dao/dao_verifier.rs
  util/dao/src/lib.rs
  util/jsonrpc-types/src/blockchain.rs
  verification/src/tests/transaction_verifier.rs
  verification/src/transaction_verifier.rs
Labels: t:ci

#4183 Fix RBF spec test failed issue
  test/src/specs/tx_pool/replace.rs
Labels: t:ci

#4178 Upgrade CI workflow's docker image to `1.71.1`
  .github/workflows/package.yaml
Labels: t:ci

#4168 chore: cargo update
  Cargo.lock
  benches/Cargo.toml
  deny.toml
  network/Cargo.toml
Labels: dependencies

#4194 Remove non-exist `error` field from `IntegrationTestImpl` rpc doc
  rpc/README.md
  rpc/src/module/test.rs
Labels: t:doc

#4201 Upgade `rustix` to `0.38.20`, fix https://github.com/nervosnetwork/ckb/security/dependabot/16
  Cargo.lock
Labels: dependencies

#4197 Replace `enum FetchCMD` by `struct FetchCMD`
  sync/src/synchronizer/mod.rs
Labels: p:could-have

#4208 Backport: Fix orphan pool issue for long pending tx
  spec/src/consensus.rs
  sync/src/types/mod.rs
  test/src/main.rs
  test/src/node.rs
  test/src/specs/tx_pool/orphan_tx.rs
  tx-pool/src/component/orphan.rs
  tx-pool/src/component/tests/mod.rs
  tx-pool/src/component/tests/orphan.rs
  tx-pool/src/pool.rs
  tx-pool/src/process.rs
Labels: hotfix

#4199 Fix orphan pool for long pending tx issues
  spec/src/consensus.rs
  sync/src/types/mod.rs
  test/src/main.rs
  test/src/node.rs
  test/src/specs/tx_pool/orphan_tx.rs
  tx-pool/src/component/orphan.rs
  tx-pool/src/component/tests/mod.rs
  tx-pool/src/component/tests/orphan.rs
  tx-pool/src/pool.rs
  tx-pool/src/process.rs
Labels: p:should-have

#4191 performance: tuning rocksdb bloom filter
  db/src/db.rs
  resource/ckb.toml
  resource/default.db-options
Labels: t:performance
