Repository nervosnetwork/ckb, pull requests merged in 2023-08, with the labels that each got.

#4089 chore(test): add ctrl handler and fix integration test timeout issue
  devtools/ci/ci_main.sh
  test/Cargo.toml
  test/src/main.rs
  test/src/node.rs
Labels: t:ci

#4091 Increase integration CI timeout to `2 hours`
  devtools/ci/ci_main.sh
  test/src/node.rs
Labels: t:ci

#4093 fix: data2 value
  rpc/README.md
  util/jsonrpc-types/src/blockchain.rs
  util/types/src/core/blockchain.rs
  util/types/src/core/tests/blockchain.rs
  util/types/src/extension/tests/check_data.rs
Labels: hotfix

#4074 Fix `FeeOfMultipleMaxBlockProposalsLimit` failed on MacOS CI action
  test/src/specs/mining/fee.rs
Labels: t:ci

#4097 BREAK CHANGE! Consensus: Allow `epoch_duration_target` to impact epoch length in `Dummy` mode.
  .github/workflows/ci_integration_tests_ubuntu.yaml
  Makefile
  spec/src/consensus.rs
  test/src/specs/dao/dao_tx.rs
  test/src/specs/dao/satoshi_dao_occupied.rs
  test/src/specs/hardfork/v2021/since.rs
  test/src/specs/hardfork/v2023/vm_version2.rs
  util/app-config/src/tests/cli_test.sh
  util/app-config/src/tests/later_bats_job/change_epoch.bats
Labels: b:consensus

#3993 Tx pool rewrite with multi_index_map
  Cargo.lock
  Makefile
  chain/src/chain.rs
  chain/src/tests/dep_cell.rs
  chain/src/tests/load_code_with_snapshot.rs
  rpc/src/module/chain.rs
  rpc/src/tests/module/pool.rs
  test/src/node.rs
  test/src/specs/mining/fee.rs
  test/src/specs/relay/transaction_relay.rs
  test/src/specs/tx_pool/collision.rs
  test/src/specs/tx_pool/different_txs_with_same_input.rs
  test/src/specs/tx_pool/get_raw_tx_pool.rs
  test/src/specs/tx_pool/limit.rs
  test/src/specs/tx_pool/pool_reconcile.rs
  test/src/specs/tx_pool/reorg_proposals.rs
  test/src/specs/tx_pool/send_tx_chain.rs
  test/src/util/mining.rs
  tx-pool/Cargo.toml
  tx-pool/src/block_assembler/mod.rs
  tx-pool/src/component/chunk.rs
  tx-pool/src/component/commit_txs_scanner.rs
  tx-pool/src/component/container.rs
  tx-pool/src/component/edges.rs
  tx-pool/src/component/entry.rs
  tx-pool/src/component/links.rs
  tx-pool/src/component/mod.rs
  tx-pool/src/component/pending.rs
  tx-pool/src/component/pool_map.rs
  tx-pool/src/component/proposed.rs
  tx-pool/src/component/score_key.rs
  tx-pool/src/component/tests/entry.rs
  tx-pool/src/component/tests/mod.rs
  tx-pool/src/component/tests/pending.rs
  tx-pool/src/component/tests/proposed.rs
  tx-pool/src/component/tests/score_key.rs
  tx-pool/src/pool.rs
  tx-pool/src/process.rs
  tx-pool/src/service.rs
  util/launcher/src/shared_builder.rs
  util/types/src/core/tx_pool.rs
Labels: t:enhancement, s:pr-created

#4099 Fix `aarch64-unknown-linux-gnu` target build instructions
  .github/workflows/package.yaml
  Makefile
Labels: t:ci

#4126 feat: notify dummy miner for new work
  miner/src/worker/dummy.rs
Labels: t:enhancement
