Repository nervosnetwork/ckb, pull requests merged in 2023-09, with the labels that each got.

#4146 Upgrade CKB's `rust-toolchain` from `1.67.1` to `1.71.1`
  .github/workflows/ci_aarch64_build_ubuntu.yaml
  .github/workflows/ci_benchmarks_ubuntu.yaml
  .github/workflows/ci_integration_tests_ubuntu.yaml
  .github/workflows/ci_linters_ubuntu.yaml
  .github/workflows/ci_quick_checks_ubuntu.yaml
  .github/workflows/ci_unit_tests_ubuntu.yaml
  .github/workflows/ci_wasm_build_ubuntu.yaml
  .github/workflows/package.yaml
  Cargo.toml
  devtools/doc/rpc.py
  docker/hub/Dockerfile
  rpc/README.md
  rust-toolchain
  sync/src/synchronizer/headers_process.rs
  sync/src/types/mod.rs
  test/src/specs/hardfork/v2023/vm_version2.rs
  util/gen-types/src/core.rs
  util/jsonrpc-types/src/blockchain.rs
  util/light-client-protocol-server/src/components/get_last_state_proof.rs
  util/light-client-protocol-server/src/tests/components/get_blocks_proof.rs
  util/types/src/core/blockchain.rs
Labels: s:waiting-on-reviewers

#4128 feat(rpc): Introduce the new method `generate_epochs` in the `IntegrationTest` module
  rpc/README.md
  rpc/src/module/test.rs
  rpc/src/tests/examples.rs
  rpc/src/tests/mod.rs
  rpc/src/tests/module/miner.rs
  rpc/src/tests/module/mod.rs
  rpc/src/tests/module/pool.rs
  rpc/src/tests/module/test.rs
Labels: t:enhancement

#4161 Remove `#[derive(Clone)]` from `Synchronizer`
  sync/src/synchronizer/block_fetcher.rs
  sync/src/synchronizer/mod.rs
  sync/src/tests/synchronizer/functions.rs
Labels: help wanted
