Repository nervosnetwork/ckb, pull requests merged in 2023-06, with the labels that each got.

#3997 `make prod-test` should specify prod features and use `nextest` instead of `cargo test`
  Makefile
Labels: t:ci

#4000 Reduce `PeerStore::load_from_dir_or_default`'s timecost
  network/src/network.rs
  network/src/peer_store/peer_store_db.rs
Labels: t:performance

#4006 chore: 2023 testnet activation params
  spec/src/hardfork.rs
  util/constant/src/hardfork/testnet.rs
Labels: u:ckb2023

#4012 Fix: `ckb init` creates config files even when an unsupported spec is specified.
  util/app-config/src/cli.rs
Labels: b:cli

#4027 Ensure `random_2_in_2_out_rtx()` suspends on first execution
  script/src/verify/tests/utils.rs
Labels: t:ci

#4034 fix: get_consensus compatibility
  rpc/README.md
  rpc/src/module/chain.rs
  util/jsonrpc-types/src/blockchain.rs
Labels: b:rpc
