Repository nervosnetwork/ckb, pull requests merged in 2023-11, with the labels that each got.

#4210 Add doc for `get_transactions` and `get_cells` RPC
  rpc/README.md
  rpc/src/module/indexer.rs
Labels: t:doc

#4203 persistence softfork cache
  .github/actions/ci_prologue/ci_prologue.sh
  .github/workflows/ci_wasm_build_ubuntu.yaml
  Cargo.lock
  Makefile
  deny.toml
  devtools/ci/ci_main.sh
  rpc/src/tests/examples.rs
  rpc/src/tests/mod.rs
  spec/Cargo.toml
  spec/src/tests/versionbits.rs
  spec/src/versionbits/mod.rs
  util/app-config/src/app_config.rs
  util/types/src/core/mod.rs
  util/types/src/global.rs
  util/types/src/lib.rs
  wasm-build-test/Cargo.toml
  wasm-build-test/src/lib.rs
Labels: t:enhancement

#4218 fix: fix vm version select
  rpc/README.md
  rpc/src/module/chain.rs
  script/src/verify.rs
  script/src/verify/tests/ckb_latest/features_since_v2019.rs
  script/src/verify/tests/ckb_latest/features_since_v2021.rs
  script/src/verify/tests/utils.rs
  spec/src/hardfork.rs
  util/constant/src/hardfork/mainnet.rs
  util/constant/src/hardfork/testnet.rs
  util/types/src/core/hardfork/ckb2021.rs
Labels: b:consensus

#4235 Move `util/launcher/src/migrate.rs` to an independent crate
  Cargo.lock
  Cargo.toml
  ckb-bin/Cargo.toml
  ckb-bin/src/subcommand/migrate.rs
  util/launcher/Cargo.toml
  util/launcher/src/lib.rs
  util/launcher/src/shared_builder.rs
  util/migrate/Cargo.toml
  util/migrate/migration-template/Cargo.toml
  util/migrate/migration-template/src/lib.rs
  util/migrate/src/lib.rs
  util/migrate/src/migrate.rs
  util/migrate/src/migrations/add_block_extension_cf.rs
  util/migrate/src/migrations/add_block_filter.rs
  util/migrate/src/migrations/add_block_filter_hash.rs
  util/migrate/src/migrations/add_chain_root_mmr.rs
  util/migrate/src/migrations/add_extra_data_hash.rs
  util/migrate/src/migrations/add_number_hash_mapping.rs
  util/migrate/src/migrations/cell.rs
  util/migrate/src/migrations/mod.rs
  util/migrate/src/migrations/table_to_struct.rs
  util/migrate/src/tests.rs
Labels: dependencies

#4238 Fix using `journalctl` to check the log of `ckb.service`
  devtools/init/linux-systemd/README.md
Labels: t:doc

#4240 Improve exit signal related log message
  block-filter/src/filter.rs
  chain/src/chain.rs
  ckb-bin/src/helper.rs
  ckb-bin/src/lib.rs
  miner/src/client.rs
  miner/src/miner.rs
  network/src/network.rs
  notify/src/lib.rs
  sync/src/synchronizer/mod.rs
  sync/src/types/header_map/mod.rs
  tx-pool/src/chunk_process.rs
  tx-pool/src/service.rs
  util/app-config/src/tests/ckb_run_replay.bats
  util/app-config/src/tests/graceful_shutdown.bats
  util/indexer/src/service.rs
  util/metrics-service/src/lib.rs
  util/stop-handler/src/stop_register.rs
Labels: t:doc
