Repository nervosnetwork/ckb, pull requests merged in 2024-09, with the labels that each got.

#4561 Recover possible transaction in conflicted cache when RBF
  test/src/main.rs
  test/src/specs/tx_pool/replace.rs
  tx-pool/src/pool.rs
  tx-pool/src/process.rs
Labels: m:tx-pool

#4626 Rename `ckb_chain::consume_unverified` to `ckb_chain::verify`
  chain/src/init.rs
  chain/src/lib.rs
  chain/src/tests/find_fork.rs
  chain/src/verify.rs
Labels: log

#4581 test: fix script test error caused by rand step cycles
  script/src/verify/tests/ckb_latest/features_since_v2021.rs
  test/src/specs/tx_pool/send_large_cycles_tx.rs
Labels: t:test: Integration Test

#4647 `get_fee_rate_statistics` should skip first (cellbase) Transaction
  rpc/src/tests/fee_rate.rs
  rpc/src/util/fee_rate.rs
Labels: b:rpc, s:backport-needed

#4648 backport # 4647 `get_fee_rate_statistics` should skip first (cellbase) Transaction
  rpc/src/tests/fee_rate.rs
  rpc/src/util/fee_rate.rs
Labels: s:backport-needed

#4635 feat: intro preview chain
  docs/hashes.toml
  resource/ckb-miner.toml
  resource/ckb.toml
  resource/specs/preview.toml
  resource/src/template.rs
Labels: b:consensus

#4654 `get_fee_rate_statistics` should aware `block_ext.txs_sizes` length is `block_ext.txs_fees` length + 1
  rpc/src/tests/fee_rate.rs
  rpc/src/util/fee_rate.rs
  util/types/src/core/extras.rs
Labels: hotfix

#4509 [Need Migration] Improve query performance of `get_cells` in rich-indexer
  Cargo.lock
  util/rich-indexer/Cargo.toml
  util/rich-indexer/resources/migrations/20240603_add_is_spent_to_output.sql
  util/rich-indexer/src/indexer/insert.rs
  util/rich-indexer/src/indexer/mod.rs
  util/rich-indexer/src/indexer/remove.rs
  util/rich-indexer/src/indexer_handle/async_indexer_handle/get_cells.rs
  util/rich-indexer/src/indexer_handle/async_indexer_handle/get_cells_capacity.rs
  util/rich-indexer/src/store.rs
Labels: t:performance, m:indexer

#4640 chore(scripts): Rename ckb_inherited_file_descriptors to ckb_inherited_fds
  script/src/verify/tests/ckb_latest/features_since_v2023.rs
  script/testdata/Makefile
  script/testdata/spawn_callee_exec_caller
  script/testdata/spawn_callee_strcat
  script/testdata/spawn_callee_strcat.c
  script/testdata/spawn_caller_current_cycles
  script/testdata/spawn_caller_out_of_cycles
  script/testdata/spawn_caller_strcat
  script/testdata/spawn_caller_strcat_wrap
  script/testdata/spawn_cases
  script/testdata/spawn_cases.c
  script/testdata/spawn_configurable_callee
  script/testdata/spawn_configurable_callee.c
  script/testdata/spawn_configurable_caller
  script/testdata/spawn_cycles
  script/testdata/spawn_cycles.c
  script/testdata/spawn_dag
  script/testdata/spawn_fuzzing
  script/testdata/spawn_fuzzing.c
  script/testdata/spawn_huge_swap.c
  script/testdata/spawn_io_cycles
  script/testdata/spawn_io_cycles.c
  script/testdata/spawn_recursive
  script/testdata/spawn_saturate_memory
  script/testdata/spawn_saturate_memory.c
  script/testdata/spawn_times
Labels: t:chore, m:vm
