Repository nervosnetwork/ckb, pull requests merged in 2024-01, with the labels that each got.

#4283 [RPC CHANGE] : Add `block_number` to `TxStatus` for `get_transaction` RPC
  rpc/README.md
  rpc/src/module/chain.rs
  util/jsonrpc-types/src/blockchain.rs
  util/types/src/core/tx_pool.rs
Labels: b:rpc

#4299 Fix the regex expression for ckb's version test
  util/app-config/src/tests/cli.bats
Labels: t:ci

#4247 feat: introduce `init_tip_hash` setting for indexer to skip previous block synchronization
  ckb-bin/src/subcommand/reset_data.rs
  resource/ckb.toml
  util/app-config/src/args.rs
  util/app-config/src/cli.rs
  util/app-config/src/configs/indexer.rs
  util/app-config/src/lib.rs
  util/indexer/src/service.rs
Labels: t:enhancement

#4300 chore: 2nd hardfork testnet activation params
  util/constant/src/hardfork/testnet.rs
Labels: b:consensus

#4305 Upgrade h2 from 0.3.21 to 0.3.24, fix RUSTSEC-2024-0003
  Cargo.lock
Labels: t:ci

#4313 chore: add how to test miner on dev chain doc
  README.md
  docs/dev-miner.md
Labels: t:doc

#4318 docs: remove an outdated wiki link in README
  README.md
Labels: t:doc

#4320 Enable the `openssl-vendored` feature for the `tentacle` package to allow CKB to statically link with OpenSSL.
  .github/workflows/package.yaml
  Cargo.lock
  network/Cargo.toml
Labels: t:ci

#4303 feat(indexer): support cell data filter
  Cargo.lock
  rpc/README.md
  rpc/src/module/indexer.rs
  util/indexer/Cargo.toml
  util/indexer/src/service.rs
  util/jsonrpc-types/src/indexer.rs
  util/jsonrpc-types/src/lib.rs
Labels: t:enhancement, m:indexer

#4326 chore: delayed 2nd hardfork testnet activation
  util/constant/src/hardfork/testnet.rs
Labels: b:consensus

#4328 Add ckb_block_process_duration in metric for monitoring and testing
  chain/src/chain.rs
  util/metrics/src/lib.rs
Labels: m:metrics

#4327 chore(scripts): update ckb-vm to v0.24.7
  .github/workflows/ci_benchmarks_windows.yaml
  .github/workflows/ci_integration_tests_windows.yaml
  .github/workflows/ci_unit_tests_windows.yaml
  .github/workflows/package.yaml
  Cargo.lock
  script/Cargo.toml
Labels: m:vm
